plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.creditcalculator'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.creditcalculator"
        minSdk 23
        targetSdk 35
        versionCode 21
        versionName "1.21"
    }

    buildTypes {
        debug {
            resValue "string", "yandex_banner_ad_unit_id", "demo-banner-yandex"
        }
        release {
            resValue "string", "yandex_banner_ad_unit_id", "R-M-19767816-1"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.biometric:biometric:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.yandex.android:mobileads:8.2.0'
    testImplementation 'junit:junit:4.13.2'
}
