package com.example.creditcalculator;

import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;

public class AboutActivity extends AppCompatActivity {
    @Override protected void attachBaseContext(Context newBase){super.attachBaseContext(AppPreferences.wrapLocale(newBase));}
    @Override protected void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);setContentView(build());}

    private View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));TextView back=top("‹",34);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView title=top(AppPreferences.tr(this,"О приложении","About"),20);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,-1,1f));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Color.TRANSPARENT);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(24),dp(20),dp(32));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));
        content.addView(text(AppPreferences.tr(this,"Финансовый калькулятор","Financial calculator"),28,R.color.text_main,true));TextView desc=text(AppPreferences.tr(this,"Расчёт кредитов, ипотеки, автокредитов, рассрочек и вкладов. Контроль реальных платежей, просрочек, напоминаний, досрочного погашения и рефинансирования.","Loan, mortgage, auto loan, installment and deposit calculations with actual payment tracking, overdue status, reminders, early repayment and refinancing."),15,R.color.text_secondary,false);LinearLayout.LayoutParams dp1=new LinearLayout.LayoutParams(-1,-2);dp1.setMargins(0,dp(8),0,dp(18));content.addView(desc,dp1);
        MaterialCardView info=card();LinearLayout ib=box(info);addLine(ib,AppPreferences.tr(this,"Версия приложения","App version"),versionName());addLine(ib,AppPreferences.tr(this,"Разработчик","Developer"),"SKRYTON");content.addView(info);
        MaterialButton guide=outline(AppPreferences.tr(this,"Инструкция по использованию","User guide"));guide.setOnClickListener(v->startActivity(new Intent(this,InstructionActivity.class)));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(54));gp.setMargins(0,dp(18),0,0);content.addView(guide,gp);MaterialButton rate=outline("★ "+AppPreferences.tr(this,"Оценить приложение","Rate the app"));rate.setOnClickListener(v->RatingHelper.openStore(this));LinearLayout.LayoutParams rtp=new LinearLayout.LayoutParams(-1,dp(54));rtp.setMargins(0,dp(10),0,0);content.addView(rate,rtp);

        MaterialCardView feedback=card();LinearLayout fb=box(feedback);fb.addView(text(AppPreferences.tr(this,"Обратная связь","Feedback"),19,R.color.text_main,true));TextView fbi=text(AppPreferences.tr(this,"Нашли ошибку или есть идея? Опишите обращение и при необходимости прикрепите фото или видео. В памяти приложения сохраняется только текст обращения — сами файлы после отправки не остаются.","Found a bug or have an idea? Describe it and optionally attach photos or video. Only request text is kept in app history; the files are not stored after sending."),14,R.color.text_secondary,false);LinearLayout.LayoutParams fip=new LinearLayout.LayoutParams(-1,-2);fip.setMargins(0,dp(7),0,dp(4));fb.addView(fbi,fip);MaterialButton bug=outline(AppPreferences.tr(this,"Сообщить об ошибке","Report a bug"));bug.setOnClickListener(v->openFeedback(FeedbackActivity.KIND_BUG));fb.addView(bug,buttonParams());MaterialButton idea=outline(AppPreferences.tr(this,"Предложить улучшение","Suggest an improvement"));idea.setOnClickListener(v->openFeedback(FeedbackActivity.KIND_IDEA));fb.addView(idea,buttonParams());MaterialButton history=outline(AppPreferences.tr(this,"Мои обращения","My requests"));history.setOnClickListener(v->startActivity(new Intent(this,FeedbackHistoryActivity.class)));fb.addView(history,buttonParams());LinearLayout.LayoutParams fcp=new LinearLayout.LayoutParams(-1,-2);fcp.setMargins(0,dp(18),0,0);content.addView(feedback,fcp);

        TextView important=text(AppPreferences.tr(this,"Важно","Important"),18,R.color.text_main,true);LinearLayout.LayoutParams itp=new LinearLayout.LayoutParams(-1,-2);itp.setMargins(0,dp(24),0,dp(6));content.addView(important,itp);content.addView(text(AppPreferences.tr(this,"Расчёты носят информационный характер и могут отличаться от расчётов банка или другой финансовой организации. Для фактического остатка, штрафов и изменений графика используйте данные вашего банка.","Calculations are for information only and may differ from a bank or other financial institution. Use your bank's figures for actual balances, penalties and schedule changes."),14,R.color.text_secondary,false));ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,bars.top,0,0);scroll.setPadding(0,0,0,bars.bottom+dp(8));return insets;});return root;}

    private void openFeedback(String kind){Intent i=new Intent(this,FeedbackActivity.class);i.putExtra(FeedbackActivity.EXTRA_KIND,kind);startActivity(i);}
    private void feedbackUnavailable(){Toast.makeText(this,AppPreferences.tr(this,"Адрес обратной связи будет добавлен позже.","The feedback address will be added later."),Toast.LENGTH_LONG).show();}
    private String versionName(){try{String v=getPackageManager().getPackageInfo(getPackageName(),0).versionName;return v==null||v.trim().isEmpty()?"1.9":v;}catch(Exception e){return "1.9";}}
    private MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));c.setRadius(dp(18));c.setStrokeColor(ContextCompat.getColor(this,R.color.border));c.setStrokeWidth(dp(1));return c;}private LinearLayout box(MaterialCardView c){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(16),dp(18),dp(16));c.addView(b);return b;}private void addLine(LinearLayout p,String l,String v){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(8),0,dp(8));p.addView(r,rp);r.addView(text(l,14,R.color.text_secondary,false),new LinearLayout.LayoutParams(0,-2,1f));r.addView(text(v,15,R.color.text_main,true));}private MaterialButton outline(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(ContextCompat.getColor(this,R.color.primary));b.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.card_background)));b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));b.setStrokeWidth(dp(1));b.setCornerRadius(dp(14));return b;}private LinearLayout.LayoutParams buttonParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(9),0,0);return p;}private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,c));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
