package com.example.creditcalculator;

import android.app.DatePickerDialog;
import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;

import java.util.Calendar;

public class EarlyRepaymentActivity extends AppCompatActivity {
    private ReminderScheduler.PaymentReminder reminder;
    private Calendar actionDate = Calendar.getInstance();
    private ScrollView scroll;
    private TextInputEditText amountInput, dateInput;
    private MaterialCardView reducePaymentCard, reduceTermCard;
    private TextView leftDot,rightDot,leftEnd,leftInterestPct,leftInterest,leftDebt,leftTotal,leftSavings,rightEnd,rightInterestPct,rightInterest,rightDebt,rightTotal,rightSavings,recommendation,afterText;
    private EditText leftPaymentEdit,leftMonthsEdit,rightPaymentEdit,rightMonthsEdit;
    private MaterialButton apply;
    private ReminderScheduler.EarlyRepaymentSimulation sim;
    private int selected = -1;
    private boolean binding;

    @Override protected void attachBaseContext(Context c){super.attachBaseContext(AppPreferences.wrapLocale(c));}
    @Override public void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);long id=getIntent().getLongExtra(PaymentDetailsActivity.EXTRA_REMINDER_ID,-1);reminder=ReminderScheduler.findById(this,id);if(reminder==null){finish();return;}actionDate.set(Calendar.HOUR_OF_DAY,0);actionDate.set(Calendar.MINUTE,0);actionDate.set(Calendar.SECOND,0);actionDate.set(Calendar.MILLISECOND,0);setContentView(build());}

    private View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(4),0,dp(12),0);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));TextView back=top("‹",34);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView title=top(AppPreferences.tr(this,"Досрочное погашение","Early repayment"),20);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,-1,1f));scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(20),dp(18),dp(30));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));
        content.addView(text(AppPreferences.tr(this,"Текущий остаток долга","Current balance"),13,R.color.text_secondary,false));TextView bal=text(FormatUtils.money(this,ReminderScheduler.remainingDebt(reminder)),27,R.color.text_main,true);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(2),0,dp(14));content.addView(bal,bp);
        amountInput=field(content,AppPreferences.tr(this,"Сумма досрочного погашения, ₽","Early repayment amount, ₽"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL,AppPreferences.tr(this,"Введите сумму, которую собираетесь внести сверх обычного графика. Она не должна превышать текущий остаток долга.","Enter the amount you plan to pay ahead of schedule. It must not exceed the current balance."));MaterialButton fullAmount=new MaterialButton(this);fullAmount.setText(AppPreferences.tr(this,"Вся сумма","Full amount"));fullAmount.setAllCaps(false);fullAmount.setTextSize(15);fullAmount.setTextColor(ContextCompat.getColor(this,R.color.primary));fullAmount.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.card_background)));fullAmount.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));fullAmount.setStrokeWidth(dp(1));fullAmount.setCornerRadius(dp(12));fullAmount.setOnClickListener(v->{double full=ReminderScheduler.balanceAtDate(reminder,actionDate.getTimeInMillis());if(full>0){amountInput.setText(num(full));amountInput.setSelection(amountInput.length());recalculate();}});LinearLayout.LayoutParams fap=new LinearLayout.LayoutParams(-1,dp(48));fap.setMargins(0,dp(-6),0,dp(4));content.addView(fullAmount,fap);TextView fullInfo=text("ⓘ "+AppPreferences.tr(this,"«Вся сумма» подставляет весь расчётный остаток долга на выбранную дату для полного досрочного погашения.","Full amount inserts the entire estimated balance for the selected date to repay the loan in full."),12,R.color.text_secondary,false);LinearLayout.LayoutParams fip=new LinearLayout.LayoutParams(-1,-2);fip.setMargins(0,0,0,dp(8));content.addView(fullInfo,fip);dateInput=field(content,AppPreferences.tr(this,"Дата досрочного погашения","Early repayment date"),InputType.TYPE_NULL,AppPreferences.tr(this,"Укажите дату фактического досрочного платежа. От неё пересчитываются остаток, срок и проценты. Если досрочное погашение делаете в день обычного платежа и банк уже списал этот платёж, сначала отметьте его «Оплачено» в графике. Расчёт учитывает статус оплаты, а не время на часах.","Choose the actual early repayment date. Balance, term and interest are recalculated from this date. If an ordinary installment is due on the same day and the bank has already charged it, mark that installment Paid first. The calculation uses payment status, not the clock time."));dateInput.setFocusable(false);dateInput.setClickable(true);dateInput.setText(FormatUtils.date(this,actionDate.getTimeInMillis()));dateInput.setOnClickListener(v->pickDate());amountInput.addTextChangedListener(new Watcher(this::recalculate));
        TextView choose=text(AppPreferences.tr(this,"Что изменить после погашения?","What should change after repayment?")+"  ⓘ",18,R.color.text_main,true);choose.setClickable(true);choose.setOnClickListener(v->showInfo(AppPreferences.tr(this,"Сравнение вариантов","Compare options"),AppPreferences.tr(this,"Слева можно уменьшить ежемесячный платёж, справа — сократить срок. Платёж и срок можно вручную поправить по данным банка. Здесь экономия считается только по процентам: страховка входит в общую переплату кредита, но не считается сэкономленной автоматически, потому что её возврат или уменьшение зависит от условий страховщика и банка. Зелёная рамка показывает вариант с большей расчётной экономией на процентах.","The left option reduces the monthly payment; the right option shortens the term. You can edit payment and term to match bank figures. Savings here are interest savings only: insurance is included in the loan's total overpayment but is not automatically treated as saved because refunds or reductions depend on the insurer and bank terms. The green frame marks the option with greater estimated interest savings.")));LinearLayout.LayoutParams chp=new LinearLayout.LayoutParams(-1,-2);chp.setMargins(0,dp(8),0,dp(10));content.addView(choose,chp);
        LinearLayout compare=new LinearLayout(this);compare.setOrientation(LinearLayout.HORIZONTAL);compare.setBaselineAligned(false);content.addView(compare,new LinearLayout.LayoutParams(-1,-2));reducePaymentCard=optionCard(true);reduceTermCard=optionCard(false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1f);lp.setMargins(0,0,dp(5),0);compare.addView(reducePaymentCard,lp);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,-2,1f);rp.setMargins(dp(5),0,0,0);compare.addView(reduceTermCard,rp);
        recommendation=text("",13,R.color.text_secondary,true);LinearLayout.LayoutParams recp=new LinearLayout.LayoutParams(-1,-2);recp.setMargins(0,dp(12),0,0);content.addView(recommendation,recp);afterText=text("",14,R.color.text_main,true);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,dp(10),0,0);content.addView(afterText,ap);
        apply=new MaterialButton(this);apply.setText(AppPreferences.tr(this,"Применить выбранный вариант","Apply selected option"));apply.setAllCaps(false);apply.setTextSize(16);apply.setTextColor(Color.WHITE);apply.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));apply.setCornerRadius(dp(14));apply.setEnabled(false);apply.setOnClickListener(v->apply());LinearLayout.LayoutParams abp=new LinearLayout.LayoutParams(-1,dp(56));abp.setMargins(0,dp(14),0,dp(8));content.addView(apply,abp);ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());Insets ime=insets.getInsets(WindowInsetsCompat.Type.ime());v.setPadding(0,bars.top,0,0);scroll.setPadding(0,0,0,Math.max(bars.bottom,ime.bottom)+dp(18));UiUtils.ensureFocusedFieldVisible(scroll);return insets;});return root;}

    private MaterialCardView optionCard(boolean left){MaterialCardView card=new MaterialCardView(this);card.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));card.setRadius(dp(15));card.setStrokeWidth(dp(2));card.setStrokeColor(ContextCompat.getColor(this,R.color.border));card.setClickable(true);card.setOnClickListener(v->{selected=left?0:1;updateSelection();});LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(12),dp(10),dp(12));card.addView(box);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);box.addView(head);TextView dot=text("○",20,R.color.primary,true);head.addView(dot,new LinearLayout.LayoutParams(dp(30),-2));TextView title=text(left?AppPreferences.tr(this,"Уменьшить ежемесячный платёж","Reduce monthly payment"):AppPreferences.tr(this,"Сократить срок","Reduce term"),14,R.color.text_main,true);head.addView(title,new LinearLayout.LayoutParams(0,-2,1f));box.addView(text(AppPreferences.tr(this,"Новый ежемесячный платёж, ₽","New monthly payment, ₽"),11,R.color.text_secondary,true),smallLine());EditText pay=smallEdit("",true);box.addView(pay,fieldParams());box.addView(text(AppPreferences.tr(this,"Новый срок, мес.","New term, months"),11,R.color.text_secondary,true),smallLine());EditText months=smallEdit("",false);box.addView(months,fieldParams());TextView end=text("",11,R.color.text_secondary,false),interestPct=text("",11,R.color.text_secondary,false),interest=text("",11,R.color.text_secondary,false),debt=text("",11,R.color.text_secondary,false),total=text("",11,R.color.text_secondary,false),savings=text("",12,R.color.text_main,true);box.addView(end,smallLine());box.addView(interestPct,smallLine());box.addView(interest,smallLine());box.addView(debt,smallLine());box.addView(total,smallLine());box.addView(savings,smallLine());if(left){leftDot=dot;leftPaymentEdit=pay;leftMonthsEdit=months;leftEnd=end;leftInterestPct=interestPct;leftInterest=interest;leftDebt=debt;leftTotal=total;leftSavings=savings;}else{rightDot=dot;rightPaymentEdit=pay;rightMonthsEdit=months;rightEnd=end;rightInterestPct=interestPct;rightInterest=interest;rightDebt=debt;rightTotal=total;rightSavings=savings;}pay.addTextChangedListener(new Watcher(this::updateCardsFromManual));months.addTextChangedListener(new Watcher(this::updateCardsFromManual));return card;}

    private void recalculate(){if(binding)return;try{double amount=positive(amountInput.getText()==null?"":amountInput.getText().toString());sim=ReminderScheduler.simulateEarlyRepayment(reminder,actionDate.getTimeInMillis(),amount);if(sim.newBalance<=.01){binding=true;leftPaymentEdit.setText("0");leftMonthsEdit.setText("0");rightPaymentEdit.setText("0");rightMonthsEdit.setText("0");binding=false;leftEnd.setText(AppPreferences.tr(this,"Кредит будет погашен полностью","Loan will be fully repaid"));rightEnd.setText(AppPreferences.tr(this,"Кредит будет погашен полностью","Loan will be fully repaid"));leftInterestPct.setText(AppPreferences.tr(this,"Остаток процентов: 0%","Interest remaining: 0%"));rightInterestPct.setText(AppPreferences.tr(this,"Остаток процентов: 0%","Interest remaining: 0%"));leftInterest.setText(AppPreferences.tr(this,"Проценты в деньгах: 0 ₽","Interest amount: 0 ₽"));rightInterest.setText(AppPreferences.tr(this,"Проценты в деньгах: 0 ₽","Interest amount: 0 ₽"));leftDebt.setText(AppPreferences.tr(this,"Остаток основного долга: 0 ₽","Principal remaining: 0 ₽"));rightDebt.setText(AppPreferences.tr(this,"Остаток основного долга: 0 ₽","Principal remaining: 0 ₽"));leftTotal.setText(AppPreferences.tr(this,"Всего осталось выплатить: 0 ₽","Total remaining payments: 0 ₽"));rightTotal.setText(AppPreferences.tr(this,"Всего осталось выплатить: 0 ₽","Total remaining payments: 0 ₽"));leftSavings.setText(AppPreferences.tr(this,"Полное погашение","Full repayment"));rightSavings.setText(AppPreferences.tr(this,"Полное погашение","Full repayment"));recommendation.setText(AppPreferences.tr(this,"После внесения этой суммы кредит будет погашен полностью.","This amount fully repays the loan."));reducePaymentCard.setStrokeColor(ContextCompat.getColor(this,R.color.success));reduceTermCard.setStrokeColor(ContextCompat.getColor(this,R.color.success));selected=0;updateSelection();afterText.setText(AppPreferences.tr(this,"Досрочно вносится: ","Early repayment: ")+FormatUtils.money(this,sim.prepayment)+AppPreferences.tr(this," → новый остаток долга: "," → new balance: ")+FormatUtils.money(this,sim.newBalance));return;}binding=true;leftPaymentEdit.setText(num(sim.reducedPayment));leftMonthsEdit.setText(String.valueOf(Math.max(1,sim.remainingMonths)));rightPaymentEdit.setText(num(sim.keptPayment));rightMonthsEdit.setText(String.valueOf(Math.max(1,sim.reducedMonths)));binding=false;updateCardsFromManual();afterText.setText(AppPreferences.tr(this,"Досрочно вносится: ","Early repayment: ")+FormatUtils.money(this,sim.prepayment)+AppPreferences.tr(this," → новый остаток долга: "," → new balance: ")+FormatUtils.money(this,sim.newBalance));}catch(Exception e){sim=null;clearCards();}}
    private void updateCardsFromManual(){if(binding||sim==null)return;try{double lp=positive(leftPaymentEdit.getText().toString());int lm=positiveInt(leftMonthsEdit.getText().toString());double rp=positive(rightPaymentEdit.getText().toString());int rm=positiveInt(rightMonthsEdit.getText().toString());double li=ReminderScheduler.interestForPaymentPlan(reminder,sim.newBalance,lm,lp),ri=ReminderScheduler.interestForPaymentPlan(reminder,sim.newBalance,rm,rp),ls=sim.oldRemainingInterest-li,rs=sim.oldRemainingInterest-ri;double lpct=sim.oldRemainingInterest<=.01?0:li/sim.oldRemainingInterest*100d,rpct=sim.oldRemainingInterest<=.01?0:ri/sim.oldRemainingInterest*100d;leftEnd.setText(AppPreferences.tr(this,"Новый срок: ","New term: ")+lm+AppPreferences.tr(this," мес. · до "," mo. · until ")+FormatUtils.date(this,endDate(sim.firstFuturePayment,lm)));leftInterestPct.setText(AppPreferences.tr(this,"Остаток процентов: ","Interest remaining: ")+Math.round(lpct)+"%");leftInterest.setText(AppPreferences.tr(this,"Проценты в деньгах: ","Interest amount: ")+FormatUtils.money(this,li));leftDebt.setText(AppPreferences.tr(this,"Остаток основного долга: ","Principal remaining: ")+FormatUtils.money(this,sim.newBalance));leftTotal.setText(AppPreferences.tr(this,"Всего осталось выплатить: ","Total remaining payments: ")+FormatUtils.money(this,sim.newBalance+li));leftSavings.setText(AppPreferences.tr(this,"Экономия: ","Savings: ")+FormatUtils.money(this,ls));rightEnd.setText(AppPreferences.tr(this,"Новый срок: ","New term: ")+rm+AppPreferences.tr(this," мес. · до "," mo. · until ")+FormatUtils.date(this,endDate(sim.firstFuturePayment,rm)));rightInterestPct.setText(AppPreferences.tr(this,"Остаток процентов: ","Interest remaining: ")+Math.round(rpct)+"%");rightInterest.setText(AppPreferences.tr(this,"Проценты в деньгах: ","Interest amount: ")+FormatUtils.money(this,ri));rightDebt.setText(AppPreferences.tr(this,"Остаток основного долга: ","Principal remaining: ")+FormatUtils.money(this,sim.newBalance));rightTotal.setText(AppPreferences.tr(this,"Всего осталось выплатить: ","Total remaining payments: ")+FormatUtils.money(this,sim.newBalance+ri));rightSavings.setText(AppPreferences.tr(this,"Экономия: ","Savings: ")+FormatUtils.money(this,rs));boolean leftBetter=ls>=rs;reducePaymentCard.setStrokeColor(ContextCompat.getColor(this,leftBetter?R.color.success:R.color.danger));reduceTermCard.setStrokeColor(ContextCompat.getColor(this,leftBetter?R.color.danger:R.color.success));recommendation.setText(leftBetter?AppPreferences.tr(this,"По расчёту выгоднее уменьшить платёж — экономия на процентах больше.","By this estimate, reducing the payment saves more interest."):AppPreferences.tr(this,"По расчёту выгоднее сократить срок — экономия на процентах больше.","By this estimate, reducing the term saves more interest."));recommendation.setTextColor(ContextCompat.getColor(this,R.color.text_secondary));updateSelection();}catch(Exception ignored){} }
    private void clearCards(){binding=true;if(leftPaymentEdit!=null){leftPaymentEdit.setText("");leftMonthsEdit.setText("");rightPaymentEdit.setText("");rightMonthsEdit.setText("");leftEnd.setText("");rightEnd.setText("");leftInterestPct.setText("");rightInterestPct.setText("");leftInterest.setText("");rightInterest.setText("");leftDebt.setText("");rightDebt.setText("");leftTotal.setText("");rightTotal.setText("");leftSavings.setText("");rightSavings.setText("");}binding=false;if(recommendation!=null)recommendation.setText("");if(afterText!=null)afterText.setText("");if(apply!=null)apply.setEnabled(false);}
    private void updateSelection(){if(leftDot==null)return;leftDot.setText(selected==0?"●":"○");rightDot.setText(selected==1?"●":"○");apply.setEnabled(sim!=null&&selected>=0);}
    private void apply(){if(sim==null||selected<0)return;try{double amount=positive(amountInput.getText().toString());if(sim.newBalance<=.01){ReminderScheduler.applyEarlyRepayment(this,reminder.id,actionDate.getTimeInMillis(),amount,false,0,0);Toast.makeText(this,AppPreferences.tr(this,"Кредит погашен полностью","Loan fully repaid"),Toast.LENGTH_LONG).show();finish();return;}double p=positive((selected==0?leftPaymentEdit:rightPaymentEdit).getText().toString());int m=positiveInt((selected==0?leftMonthsEdit:rightMonthsEdit).getText().toString());ReminderScheduler.applyEarlyRepayment(this,reminder.id,actionDate.getTimeInMillis(),amount,selected==1,p,m);Toast.makeText(this,AppPreferences.tr(this,"Досрочное погашение применено","Early repayment applied"),Toast.LENGTH_LONG).show();finish();}catch(Exception e){Toast.makeText(this,AppPreferences.tr(this,"Проверьте введённые значения","Check the entered values"),Toast.LENGTH_SHORT).show();}}
    private void pickDate(){new DatePickerDialog(this,(d,y,m,day)->{actionDate.set(y,m,day,12,0,0);dateInput.setText(FormatUtils.date(this,actionDate.getTimeInMillis()));recalculate();},actionDate.get(Calendar.YEAR),actionDate.get(Calendar.MONTH),actionDate.get(Calendar.DAY_OF_MONTH)).show();}
    private long endDate(long first,int months){return ReminderScheduler.buildDueDate(first,Math.max(0,months-1)).getTimeInMillis();}

    private LinearLayout infoLabelRow(String title,String message){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(title,14,R.color.text_secondary,true),new LinearLayout.LayoutParams(0,-2,1f));TextView i=text("ⓘ",21,R.color.primary,true);i.setGravity(Gravity.CENTER);i.setClickable(true);i.setOnClickListener(v->showInfo(title,message));row.addView(i,new LinearLayout.LayoutParams(dp(40),dp(40)));return row;}
    private void showInfo(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton(AppPreferences.tr(this,"Понятно","OK"),null).show();}
    private TextInputEditText field(LinearLayout p,String hint,int type,String help){p.addView(infoLabelRow(hint,help));TextInputLayout l=new TextInputLayout(this);l.setBoxBackgroundMode(TextInputLayout.BOX_BACKGROUND_OUTLINE);l.setBoxStrokeColor(ContextCompat.getColor(this,R.color.primary));l.setBoxCornerRadii(dp(14),dp(14),dp(14),dp(14));TextInputEditText e=new TextInputEditText(this);e.setInputType(type);e.setSingleLine(true);e.setTextColor(ContextCompat.getColor(this,R.color.text_main));l.addView(e,new TextInputLayout.LayoutParams(-1,dp(58)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));p.addView(l,lp);if(hint.contains("₽"))UiUtils.attachMoneyFormatting(e);UiUtils.keepFieldVisibleOnFocus(scroll,e);return e;}private EditText smallEdit(String hint,boolean money){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(12);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setTextColor(ContextCompat.getColor(this,R.color.text_main));e.setHintTextColor(ContextCompat.getColor(this,R.color.text_secondary));if(money)UiUtils.attachMoneyFormatting(e);UiUtils.keepFieldVisibleOnFocus(scroll,e);return e;}private LinearLayout.LayoutParams fieldParams(){return new LinearLayout.LayoutParams(-1,dp(48));}private LinearLayout.LayoutParams smallLine(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,0);return p;}private double positive(String s){double d=Double.parseDouble(clean(s));if(d<=0)throw new IllegalArgumentException();return d;}private int positiveInt(String s){int v=Integer.parseInt(clean(s).split("\\.")[0]);if(v<=0)throw new IllegalArgumentException();return v;}private String clean(String s){return s==null?"":s.replace(" ","").replace("\u00A0","").replace("\u202F","").replace(',','.').trim();}private String num(double d){return String.format(java.util.Locale.US,"%.2f",d).replace('.',',');}
    private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,c));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private static class Watcher implements TextWatcher{private final Runnable r;Watcher(Runnable r){this.r=r;}public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){}public void afterTextChanged(Editable e){if(r!=null)r.run();}}
}
