package com.example.creditcalculator;

import android.content.Context;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.android.material.card.MaterialCardView;

public class InstructionActivity extends AppCompatActivity {
    @Override protected void attachBaseContext(Context c){super.attachBaseContext(AppPreferences.wrapLocale(c));}
    @Override protected void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);setContentView(build());}

    private View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));TextView back=top("‹",34);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView title=top(local("Инструкция","User guide","Kullanım kılavuzu","Instrucciones"),20);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,-1,1f));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(22),dp(20),dp(32));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));content.addView(text(local("Как пользоваться приложением","How to use the app","Uygulama nasıl kullanılır","Cómo usar la aplicación"),27,R.color.text_main,true));TextView intro=text(local("Все основные функции текущей версии.","All main functions in the current version.","Mevcut sürümdeki tüm ana işlevler.","Todas las funciones principales de la versión actual."),15,R.color.text_secondary,false);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,dp(6),0,dp(16));content.addView(intro,ip);

        section(content,"1",local("Первый запуск и язык","First launch and language","İlk açılış ve dil","Primer inicio e idioma"),local(
                "При первом запуске выберите Русский, English, Türkçe или Español. Выбор сохраняется и больше не спрашивается. Позже язык можно изменить в Настройки → Язык приложения. После полного сброса выбор языка появится снова.",
                "On first launch choose Russian, English, Turkish or Spanish. The choice is saved and is not asked again. You can change it later in Settings → App language. A full reset shows the language screen again.",
                "İlk açılışta Rusça, İngilizce, Türkçe veya İspanyolca seçin. Seçim kaydedilir ve tekrar sorulmaz. Daha sonra Ayarlar → Uygulama dili bölümünden değiştirebilirsiniz. Tam sıfırlamadan sonra dil ekranı yeniden görünür.",
                "En el primer inicio elige ruso, inglés, turco o español. La selección se guarda y no vuelve a preguntarse. Puedes cambiarla después en Ajustes → Idioma. Tras un restablecimiento completo, volverá a aparecer la selección de idioma."));
        section(content,"2",local("Калькуляторы","Calculators","Hesaplayıcılar","Calculadoras"),local(
                "Доступны кредит, ипотека, автокредит, рассрочка и вклад. Для кредита, ипотеки, автокредита и рассрочки можно указать страховку. Переключатель определяет, включена ли страховка в сумму финансирования или оплачивается отдельно.",
                "Loan, mortgage, auto loan, installment and deposit calculators are available. Loan types and installments can include insurance. The switch controls whether insurance is financed or paid separately.",
                "Kredi, konut kredisi, araç kredisi, taksit ve mevduat hesaplayıcıları vardır. Kredi türleri ve taksitlerde sigorta girilebilir. Anahtar, sigortanın finansmana dahil mi yoksa ayrı mı ödendiğini belirler.",
                "Hay calculadoras de préstamo, hipoteca, auto, cuotas y depósito. Los préstamos y las cuotas admiten seguro. El interruptor indica si el seguro se financia o se paga por separado."));
        section(content,"3",local("Аннуитетный и дифференцированный платёж","Annuity and differential payments","Eşit ve azalan taksitler","Cuota fija y decreciente"),local(
                "Для кредита, ипотеки и автокредита выберите тип платежей. Аннуитетный — плановый платёж примерно одинаковый каждый месяц. Дифференцированный — основной долг гасится равными частями, поэтому платёж постепенно уменьшается. Весь график, проценты и остаток рассчитываются по выбранному типу.",
                "For loans, mortgages and auto loans choose a payment type. Annuity uses roughly equal monthly payments. Differential repays equal principal portions so payments decrease over time. The whole schedule, interest and balance follow the selected type.",
                "Kredi, konut ve araç kredilerinde ödeme türünü seçin. Eşit taksitli yöntemde aylık ödeme yaklaşık aynıdır. Azalan taksitli yöntemde anapara eşit parçalarla ödenir ve taksit zamanla azalır. Plan, faiz ve kalan borç seçime göre hesaplanır.",
                "Para préstamos, hipotecas y auto elige el tipo de pago. La cuota fija mantiene pagos mensuales similares. La cuota decreciente amortiza capital en partes iguales y el pago baja con el tiempo. El calendario, intereses y saldo se calculan según el tipo elegido."));
        section(content,"4",local("Добавление записи и старый кредит","Adding an item and an existing loan","Kayıt ve mevcut kredi ekleme","Añadir un registro y un préstamo existente"),local(
                "Нажмите +, заполните условия и выберите дату первого платежа. Прошедшая дата разрешена. Если часть графика уже в прошлом, приложение спросит, были ли эти платежи оплачены по графику. Можно отметить их оплаченными сразу или оставить неоплаченными — тогда они станут просроченными.",
                "Tap +, enter the terms and choose the first payment date. Past dates are allowed. If part of the schedule is already in the past, the app asks whether those payments were paid. Mark them paid or leave them unpaid, in which case they become overdue.",
                "+ düğmesine basın, koşulları girin ve ilk ödeme tarihini seçin. Geçmiş tarih kullanılabilir. Planın bir kısmı geçmişteyse uygulama bu ödemelerin yapılıp yapılmadığını sorar. Ödendi olarak işaretleyebilir veya ödenmemiş bırakabilirsiniz; bu durumda gecikmiş sayılırlar.",
                "Pulsa +, introduce las condiciones y elige la fecha del primer pago. Se permiten fechas pasadas. Si parte del calendario ya pasó, la app preguntará si esos pagos se realizaron. Puedes marcarlos pagados o dejarlos pendientes; en ese caso quedarán vencidos."));
        section(content,"5",local("Напоминания","Reminders","Hatırlatmalar","Recordatorios"),local(
                "Укажите, за сколько дней и в какое время напомнить. Если время не менялось, используется 09:00 по времени телефона. Предварительное уведомление не отменяет уведомление в день платежа. В уведомлении доступны «Платёж оплачен» и «Напомнить позже». Перенос: 5, 10, 15, 30 минут, 1 час или выбранное вручную время.",
                "Choose how many days before and at what time to remind you. If unchanged, 09:00 local device time is used. The advance reminder does not replace the payment-day reminder. Notifications offer Payment paid and Remind later. Snooze for 5, 10, 15, 30 minutes, 1 hour or a manually chosen time.",
                "Kaç gün önce ve hangi saatte hatırlatılacağını seçin. Değiştirilmezse telefonun yerel saatine göre 09:00 kullanılır. Ön hatırlatma, ödeme günü bildirimini kaldırmaz. Bildirimde Ödeme yapıldı ve Daha sonra hatırlat seçenekleri vardır. 5, 10, 15, 30 dakika, 1 saat veya elle seçilen saate erteleyebilirsiniz.",
                "Elige cuántos días antes y a qué hora recibir el aviso. Si no se cambia, se usa 09:00 según la hora local del teléfono. El aviso previo no sustituye al aviso del día de pago. La notificación ofrece Pago realizado y Recordar más tarde: 5, 10, 15, 30 minutos, 1 hora o una hora manual."));
        section(content,"6",local("Статусы, цвета и смайлики","Statuses, colors and smileys","Durumlar, renkler ve yüzler","Estados, colores y caritas"),local(
                "Платёж может быть: предстоящий, сегодня, просрочен или оплачен. Прошедшая дата сама по себе не означает оплату. В общей сводке используется только цветной смайлик: зелёный ☺ — всё хорошо; жёлтый ☻ — до платежа ещё есть время; красный ☹ — нужно оплатить скоро или есть просрочка. Строка следующего платежа использует те же цвета.",
                "A payment can be upcoming, due today, overdue or paid. A past date does not automatically mean paid. The summary uses only a colored smiley: green ☺ means all good; yellow ☻ means there is still time; red ☹ means payment is due soon or overdue. The next-payment line uses the same colors.",
                "Ödeme yaklaşan, bugün, gecikmiş veya ödenmiş olabilir. Tarihin geçmiş olması otomatik olarak ödeme yapıldığı anlamına gelmez. Genel özette yalnızca renkli yüz kullanılır: yeşil ☺ her şey iyi; sarı ☻ ödeme için zaman var; kırmızı ☹ ödeme yakında gerekli veya gecikmiş ödeme var. Sonraki ödeme satırı da aynı renkleri kullanır.",
                "Un pago puede estar próximo, vencer hoy, estar vencido o pagado. Una fecha pasada no significa automáticamente que esté pagado. El resumen usa solo una carita de color: verde ☺ todo bien; amarilla ☻ aún hay tiempo; roja ☹ hay que pagar pronto o existe un vencido. La línea del próximo pago usa los mismos colores."));
        section(content,"7",local("Общая сводка и сортировка","Summary and sorting","Genel özet ve sıralama","Resumen y ordenación"),local(
                "В «Мои платежи» показаны общий остаток долга, сумма к оплате в этом месяце, сколько уже оплачено и сколько осталось, просрочка и ближайший обязательный платёж. Сортировка при каждом новом входе начинается с «Ближайший платёж» и не сохраняется. Фильтр и дополнительные способы сортировки доступны отдельными кнопками.",
                "My payments shows total debt, due this month, paid and remaining amounts, overdue totals and the next required payment. Sorting resets to Nearest payment each time you re-enter the page and is not saved. Filter and other sorting choices are separate controls.",
                "Ödemelerim ekranında toplam borç, bu ay ödenecek tutar, ödenen ve kalan tutar, gecikmeler ve en yakın zorunlu ödeme gösterilir. Sayfaya her yeniden girişte sıralama En yakın ödeme olarak başlar ve kaydedilmez. Filtre ve diğer sıralama seçenekleri ayrıdır.",
                "Mis pagos muestra deuda total, importe del mes, pagado, pendiente, vencidos y el próximo pago obligatorio. Cada vez que vuelves a la página la ordenación se reinicia a Pago más próximo y no se guarda. El filtro y otras opciones de ordenación están separados."));
        section(content,"8",local("График платежей и архив","Payment schedule and archive","Ödeme planı ve arşiv","Calendario de pagos y archivo"),local(
                "В подробностях оплаченные старые платежи скрыты по умолчанию. Нажмите «Архив» справа от заголовка графика, чтобы показать их; при выходе из записи архив снова скрывается. Неоплаченные просроченные платежи не прячутся. Нажмите на строку платежа, чтобы увидеть основной долг, проценты и остаток после платежа.",
                "In details, old paid payments are hidden by default. Tap Archive beside the schedule title to show them; leaving the item hides them again. Unpaid overdue installments stay visible. Tap a payment row to see principal, interest and balance after payment.",
                "Ayrıntılarda eski ödenmiş taksitler varsayılan olarak gizlidir. Plan başlığının yanındaki Arşiv düğmesiyle gösterin; kayıttan çıkınca tekrar gizlenir. Ödenmemiş gecikmiş taksitler gizlenmez. Anapara, faiz ve ödeme sonrası bakiyeyi görmek için satıra dokunun.",
                "En los detalles, los pagos antiguos ya pagados se ocultan por defecto. Pulsa Archivo junto al título del calendario para mostrarlos; al salir volverán a ocultarse. Los vencidos sin pagar permanecen visibles. Pulsa una fila para ver capital, intereses y saldo posterior."));
        section(content,"9",local("Изменение суммы и фактическая оплата","Changing a scheduled amount and actual payment","Plan tutarı ve gerçek ödeme","Cambiar importe previsto y pago real"),local(
                "В раскрытом платеже можно изменить плановую сумму. Выберите: только этот платёж или этот и все следующие; затем отдельно решите, менять ли архивные платежи. Фактически оплаченная сумма при этом не меняется. Для реальной оплаты укажите сумму, дату и при необходимости штраф/пеню. Частичная оплата не закрывает платёж полностью.",
                "An expanded payment lets you change the planned amount. Apply it only to this payment or to this and all following payments, then separately choose whether archived payments are included. Actual paid amounts do not change. For a real payment enter amount, date and optional penalty. A partial payment does not fully close the installment.",
                "Açılan ödeme satırında planlanan tutarı değiştirebilirsiniz. Yalnızca bu ödeme veya bu ve sonraki tüm ödemeler seçilir; ardından arşivdekilerin de değişip değişmeyeceği ayrıca sorulur. Gerçekte ödenen tutar değişmez. Gerçek ödeme için tutar, tarih ve gerekirse ceza girin. Kısmi ödeme taksiti tamamen kapatmaz.",
                "En una fila desplegada puedes cambiar el importe previsto: solo este pago o este y todos los siguientes, y después decidir por separado si incluir los archivados. El importe realmente pagado no cambia. Para registrar un pago real indica importe, fecha y, si procede, penalización. Un pago parcial no cierra completamente la cuota."));
        section(content,"10",local("Досрочное погашение","Early repayment","Erken ödeme","Amortización anticipada"),local(
                "Откройте отдельную страницу «Досрочное погашение», введите сумму и дату. Слева и справа сравниваются уменьшение ежемесячного платежа и сокращение срока. Можно поправить рассчитанные платёж и срок по данным банка. Зелёная рамка показывает более выгодный по процентам вариант, красная — меньшую экономию. Приложение ничего не выбирает за вас: отметьте вариант и нажмите «Применить выбранный вариант».",
                "Open the Early repayment page and enter amount and date. Reducing the monthly payment and reducing the term are compared side by side. You may edit calculated payment and term to match bank figures. Green means greater interest savings and red means less. The app never chooses for you: select an option and tap Apply selected option.",
                "Erken ödeme sayfasında tutar ve tarihi girin. Aylık ödemeyi azaltma ve vadeyi kısaltma yan yana karşılaştırılır. Banka verilerine uyması için hesaplanan ödeme ve vadeyi değiştirebilirsiniz. Yeşil çerçeve daha fazla faiz tasarrufunu, kırmızı daha azını gösterir. Uygulama sizin yerinize seçim yapmaz; seçeneği işaretleyip Uygula'ya basın.",
                "Abre Amortización anticipada e introduce importe y fecha. Se comparan lado a lado reducir la cuota y reducir el plazo. Puedes corregir cuota y plazo según los datos del banco. El borde verde indica mayor ahorro de intereses y el rojo menor ahorro. La app no decide por ti: selecciona una opción y pulsa Aplicar."));
        section(content,"11",local("Рефинансирование","Refinancing","Yeniden finansman","Refinanciación"),local(
                "На отдельной странице укажите новую ставку, срок, комиссию, страховку, дату и при необходимости новую сумму кредита. Приложение сравнит текущий кредит и рефинансирование, включая дополнительные расходы и будущие выплаты. Зелёная рамка показывает более выгодный расчёт, но окончательное решение всегда выбирает пользователь.",
                "On the separate page enter new rate, term, commission, insurance, date and, if needed, a new loan amount. The app compares keeping the current loan with refinancing, including extra costs and future payments. Green marks the cheaper estimate, but the final choice is always yours.",
                "Ayrı sayfada yeni faiz, vade, komisyon, sigorta, tarih ve gerekirse yeni kredi tutarını girin. Uygulama mevcut kredi ile yeniden finansmanı ek masraflar ve gelecekteki ödemeler dahil karşılaştırır. Yeşil daha avantajlı hesabı gösterir ancak son karar her zaman kullanıcıya aittir.",
                "En la página separada introduce nuevo interés, plazo, comisión, seguro, fecha y, si hace falta, nuevo importe del préstamo. La app compara mantener el préstamo con refinanciar, incluidos gastos y pagos futuros. El verde marca el cálculo más favorable, pero la decisión final siempre es del usuario."));
        section(content,"12",local("История, архив и корзина","History, archive and trash","Geçmiş, arşiv ve çöp kutusu","Historial, archivo y papelera"),local(
                "История изменений сохраняет создание записи, редактирование, фактические оплаты, изменения графика, досрочные погашения, рефинансирования и перемещения. Архив предназначен для неактивных записей. Корзина хранит удалённые записи до 30 дней и позволяет восстановить их.",
                "Change history records creation, edits, actual payments, schedule changes, early repayments, refinancing and moves. Archive holds inactive items. Trash keeps deleted items for up to 30 days and allows restoration.",
                "Değişiklik geçmişi oluşturma, düzenleme, gerçek ödemeler, plan değişiklikleri, erken ödeme, yeniden finansman ve taşımaları kaydeder. Arşiv pasif kayıtlar içindir. Çöp kutusu silinen kayıtları 30 güne kadar tutar ve geri yüklemeye izin verir.",
                "El historial guarda creación, ediciones, pagos reales, cambios del calendario, amortizaciones anticipadas, refinanciaciones y movimientos. Archivo contiene registros inactivos. Papelera conserva eliminados hasta 30 días y permite restaurarlos."));
        section(content,"13",local("Безопасность","Security","Güvenlik","Seguridad"),local(
                "В Настройки → Безопасность включите защиту приложения и установите PIN из 4–6 цифр или пароль. Если устройство поддерживает, можно включить биометрию. Автоблокировка: сразу, через 1, 5 или 15 минут после ухода из приложения. Это защищает записи от случайных изменений другим человеком.",
                "In Settings → Security enable app protection and set a 4–6 digit PIN or password. Biometrics can be enabled on supported devices. Auto-lock can be immediate or after 1, 5 or 15 minutes away from the app. This protects records from accidental changes by another person.",
                "Ayarlar → Güvenlik bölümünde korumayı açın ve 4–6 haneli PIN veya parola belirleyin. Desteklenen cihazlarda biyometri açılabilir. Otomatik kilit hemen, 1, 5 veya 15 dakika sonra çalışabilir. Bu, kayıtları başka bir kişinin yanlışlıkla değiştirmesine karşı korur.",
                "En Ajustes → Seguridad activa la protección y establece un PIN de 4–6 dígitos o una contraseña. En dispositivos compatibles puedes activar biometría. El bloqueo automático puede ser inmediato o tras 1, 5 o 15 minutos fuera de la app. Así se evitan cambios accidentales por otras personas."));
        section(content,"14",local("Резервная копия и полный сброс","Backup and full reset","Yedekleme ve tam sıfırlama","Copia de seguridad y restablecimiento"),local(
                "Резервная копия .fcalc включает записи, статусы оплат, историю, напоминания, настройки и профиль. Её можно сохранить без пароля или зашифровать паролем. Полный сброс в Настройках требует двух подтверждений и удаляет данные приложения, но не удаляет уже сохранённые файлы резервных копий на телефоне.",
                "A .fcalc backup includes records, payment statuses, history, reminders, settings and profile. Save it plain or password-encrypted. Full reset in Settings requires two confirmations and deletes app data, but does not delete backup files already stored on your phone.",
                ".fcalc yedeği kayıtları, ödeme durumlarını, geçmişi, hatırlatmaları, ayarları ve profili içerir. Parolasız veya parola ile şifreli kaydedilebilir. Ayarlardaki tam sıfırlama iki onay ister ve uygulama verilerini siler, ancak telefonda daha önce kaydedilmiş yedek dosyalarını silmez.",
                "La copia .fcalc incluye registros, estados de pago, historial, recordatorios, ajustes y perfil. Puede guardarse sin contraseña o cifrada. El restablecimiento completo requiere dos confirmaciones y elimina los datos de la app, pero no borra los archivos de copia ya guardados en el teléfono."));
        section(content,"15",local("Обратная связь","Feedback","Geri bildirim","Comentarios"),local(
                "В «О приложении» находятся «Сообщить об ошибке» и «Предложить улучшение». Пока адрес связи ещё не добавлен, приложение сообщит об этом. После подключения почты здесь можно будет отправлять ошибки, идеи и советы по улучшению.",
                "About contains Report a bug and Suggest an improvement. Until a contact address is configured, the app tells you it is not available yet. Once email is connected, this will be the place for bugs, feature ideas and improvement suggestions.",
                "Uygulama hakkında bölümünde Hata bildir ve İyileştirme öner seçenekleri vardır. İletişim adresi henüz eklenmediği sürece uygulama bunu bildirir. E-posta bağlandığında hata, özellik fikri ve geliştirme önerileri buradan gönderilebilir.",
                "En Acerca de están Informar de un error y Sugerir una mejora. Mientras no haya dirección de contacto, la app lo indicará. Cuando se añada el correo, aquí se podrán enviar errores, ideas de funciones y sugerencias."));
        section(content,"!",local("Точность расчётов","Calculation accuracy","Hesap doğruluğu","Precisión de los cálculos"),local(
                "Банк может использовать другие правила округления, даты начисления процентов, комиссии, страховки и условия договора. Поэтому приложение является помощником для расчёта и контроля, а фактические данные банка можно вручную внести в график.",
                "Banks may use different rounding, interest dates, fees, insurance and contract rules. The app is a calculation and tracking assistant; actual bank figures can be entered manually into the schedule.",
                "Bankalar farklı yuvarlama, faiz tarihleri, komisyon, sigorta ve sözleşme kuralları kullanabilir. Bu nedenle uygulama hesaplama ve takip yardımcısıdır; bankanın gerçek verileri plana elle girilebilir.",
                "Los bancos pueden usar otros redondeos, fechas de intereses, comisiones, seguros y condiciones. Por eso la app es una ayuda de cálculo y control; los datos reales del banco pueden introducirse manualmente en el calendario."));

        ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,bars.top,0,0);scroll.setPadding(0,0,0,bars.bottom+dp(8));return insets;});return root;}

    private String local(String ru,String en,String tr,String es){String l=AppPreferences.getLanguage(this);if("en".equals(l))return en;if("tr".equals(l))return tr;if("es".equals(l))return es;return ru;}
    private void section(LinearLayout parent,String number,String title,String body){MaterialCardView card=new MaterialCardView(this);card.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));card.setRadius(dp(16));card.setStrokeColor(ContextCompat.getColor(this,R.color.border));card.setStrokeWidth(dp(1));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(14),dp(16),dp(14));card.addView(box);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);box.addView(row);TextView badge=text(number,14,R.color.white,true);badge.setGravity(Gravity.CENTER);badge.setBackgroundResource(R.drawable.circle_primary);row.addView(badge,new LinearLayout.LayoutParams(dp(36),dp(36)));TextView t=text(title,18,R.color.text_main,true);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1f);tp.setMargins(dp(12),0,0,0);row.addView(t,tp);TextView b=text(body,14,R.color.text_secondary,false);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(10),0,0);box.addView(b,bp);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(10));parent.addView(card,cp);}
    private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,c));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
