package com.example.creditcalculator;

import android.content.Context;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.android.material.card.MaterialCardView;

public class InstructionActivity extends AppCompatActivity {
    @Override protected void attachBaseContext(Context c){super.attachBaseContext(AppPreferences.wrapLocale(c));}
    @Override protected void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);setContentView(build());}

    private View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));TextView back=top("‹",34);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView title=top(local("Инструкция","User guide","Kullanım kılavuzu","Instrucciones"),20);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,-1,1f));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(22),dp(20),dp(32));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));content.addView(text(local("Как пользоваться приложением","How to use the app","Uygulama nasıl kullanılır","Cómo usar la aplicación"),27,R.color.text_main,true));TextView intro=text(local("Все основные функции текущей версии.","All main functions in the current version.","Mevcut sürümdeki tüm ana işlevler.","Todas las funciones principales de la versión actual."),15,R.color.text_secondary,false);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,dp(6),0,dp(16));content.addView(intro,ip);

        section(content,"1",local("Первый запуск и язык","First launch and language","İlk açılış ve dil","Primer inicio e idioma"),local(
                "При первом запуске выберите Русский, English, Türkçe или Español. Выбор сохраняется и больше не спрашивается. Позже язык можно изменить в Настройки → Язык приложения. После полного сброса выбор языка появится снова. При обычном входе после проверки защиты приложение напрямую открывает раздел «Мои платежи». Калькуляторы остаются доступны через боковое меню. В «Мои платежи» меню выезжает слева и затемняет остальную часть экрана.",
                "On first launch choose Russian, English, Turkish or Spanish. The choice is saved and is not asked again. You can change it later in Settings → App language. A full reset shows the language screen again.",
                "İlk açılışta Rusça, İngilizce, Türkçe veya İspanyolca seçin. Seçim kaydedilir ve tekrar sorulmaz. Daha sonra Ayarlar → Uygulama dili bölümünden değiştirebilirsiniz. Tam sıfırlamadan sonra dil ekranı yeniden görünür.",
                "En el primer inicio elige ruso, inglés, turco o español. La selección se guarda y no vuelve a preguntarse. Puedes cambiarla después en Ajustes → Idioma. Tras un restablecimiento completo, volverá a aparecer la selección de idioma."));
        section(content,"2",local("Калькуляторы","Calculators","Hesaplayıcılar","Calculadoras"),local(
                "На странице «Калькуляторы» доступны кредит, ипотека, автокредит, рассрочка и вклад. Досрочный платёж выполняется из соответствующего раздела записи/меню, а добавление новой записи — кнопкой + в «Мои платежи». Для кредита, ипотеки, автокредита и рассрочки можно указать страховку. Денежные суммы при вводе автоматически разделяются пробелами, например 5 000 000. Пробелы не влияют на расчёт.",
                "Loan, mortgage, auto loan, installment and deposit calculators are available. Insurance can be added where applicable. Money fields are grouped with spaces while typing, for example 5 000 000; grouping does not affect calculations.",
                "Kredi, konut kredisi, araç kredisi, taksit ve mevduat hesaplayıcıları vardır. Uygun alanlarda sigorta girilebilir. Para tutarları yazarken 5 000 000 örneğindeki gibi boşluklarla gruplanır; bu hesaplamayı etkilemez.",
                "Hay calculadoras de préstamo, hipoteca, auto, cuotas y depósito. Se puede añadir seguro donde corresponda. Los importes se agrupan con espacios al escribir, por ejemplo 5 000 000; esto no cambia el cálculo."));
        section(content,"3",local("Аннуитетный и дифференцированный платёж","Annuity and differential payments","Eşit ve azalan taksitler","Cuota fija y decreciente"),local(
                "Для кредита, ипотеки и автокредита выберите тип платежей. Аннуитетный — плановый платёж примерно одинаковый каждый месяц. Дифференцированный — основной долг гасится равными частями, поэтому платёж постепенно уменьшается. Весь график, проценты и остаток рассчитываются по выбранному типу.",
                "For loans, mortgages and auto loans choose a payment type. Annuity uses roughly equal monthly payments. Differential repays equal principal portions so payments decrease over time. The whole schedule, interest and balance follow the selected type.",
                "Kredi, konut ve araç kredilerinde ödeme türünü seçin. Eşit taksitli yöntemde aylık ödeme yaklaşık aynıdır. Azalan taksitli yöntemde anapara eşit parçalarla ödenir ve taksit zamanla azalır. Plan, faiz ve kalan borç seçime göre hesaplanır.",
                "Para préstamos, hipotecas y auto elige el tipo de pago. La cuota fija mantiene pagos mensuales similares. La cuota decreciente amortiza capital en partes iguales y el pago baja con el tiempo. El calendario, intereses y saldo se calculan según el tipo elegido."));
        section(content,"4",local("Добавление записи и проверка полей","Adding an item and field validation","Kayıt ekleme ve alan kontrolü","Añadir un registro y validar campos"),local(
                "Нажмите + и заполните условия. Если значение введено неверно, ошибка показывается у конкретного поля, а форма прокручивается к нему. При открытой клавиатуре активное поле автоматически остаётся над клавиатурой. Прошедшая дата первого платежа разрешена: приложение спросит, были ли прошлые платежи оплачены.",
                "Tap + and enter the terms. Invalid values are shown next to the exact field and the form scrolls to it. The focused field is kept above the keyboard. A past first-payment date is allowed; the app then asks whether earlier payments were paid.",
                "+ düğmesine basın ve koşulları doldurun. Hatalı değer ilgili alanın yanında gösterilir ve form o alana kayar. Aktif alan klavyenin üstünde tutulur. Geçmiş ilk ödeme tarihi kullanılabilir; uygulama önceki ödemelerin yapılıp yapılmadığını sorar.",
                "Pulsa + e introduce las condiciones. Los valores no válidos se indican junto al campo exacto y el formulario se desplaza hasta él. El campo activo permanece encima del teclado. Se permite una fecha inicial pasada; la app preguntará si los pagos anteriores se realizaron."));
        section(content,"5",local("Напоминания в день платежа","Payment-day reminders","Ödeme günü hatırlatmaları","Recordatorios el día de pago"),local(
                "Укажите, за сколько дней и в какое время напомнить. В день платежа с 00:00 в шторке появляется постоянное беззвучное уведомление — это не будильник. Оно принудительно без звука, не убирается свайпом и закрывается только после отметки «Оплачено». В выбранное время запускается отдельное звуковое напоминание, только если платёж ещё не отмечен. Если приложение запущено уже после выбранного времени, пропущенный будильник не запускается задним числом. Предварительные уведомления до даты платежа остаются обычными напоминаниями.",
                "Choose how many days before and at what time to remind you. On the payment day a persistent silent notification appears from 00:00; it is not an alarm. It stays until you mark the payment paid. Remind later schedules another reminder but does not remove the silent day notice. If the payment is still unresolved at the selected time, a separate sound reminder is triggered. Advance reminders before the due date remain normal reminders.",
                "Kaç gün önce ve hangi saatte hatırlatma istediğinizi seçin; varsayılan saat 09:00'dır. Ön bildirimlerde Ödendi düğmesi yoktur. Ödeme gününde 00:00’dan itibaren sessiz ve kalıcı bir bildirim görünür. Bu bildirim yalnızca ödeme ödendi olarak işaretlenince kaldırılır. Seçilen saatte ödeme hâlâ açık ise ayrı bir sesli hatırlatma çalışır.",
                "Elige cuántos días antes y a qué hora; la hora predeterminada es 09:00. Los avisos previos no muestran Ya pagado. El día del pago aparece desde las 00:00 una notificación silenciosa y persistente. Solo desaparece al marcar el pago como pagado. Si a la hora elegida sigue pendiente, se lanza un recordatorio sonoro independiente."));
        section(content,"6",local("Статусы, цвета и смайлики","Statuses, colors and smileys","Durumlar, renkler ve yüzler","Estados, colores y caritas"),local(
                "Платёж может быть предстоящим, сегодня, просроченным или оплаченным. Цвет сводки зависит от ближайшего неоплаченного платежа: больше 7 дней — зелёный ☺; от 7 до 4 дней — жёлтый ☻; 3 дня или меньше — красный ☹. Просрочка всегда красная. Если ближайший платёж далеко и текущий месяц закрыт, смайлик зелёный.",
                "A payment can be upcoming, due today, overdue or paid. Summary color follows the nearest unpaid payment: more than 7 days is green ☺; 7 to 4 days is yellow ☻; 3 days or less is red ☹. Any overdue payment is red. If the next payment is far away and this month is settled, the face is green.",
                "Ödeme yaklaşan, bugün, gecikmiş veya ödenmiş olabilir. Renk en yakın ödenmemiş taksite göre belirlenir: 7 günden fazla yeşil ☺; 7–4 gün sarı ☻; 3 gün veya daha az kırmızı ☹. Gecikme her zaman kırmızıdır. Bu ay kapalı ve sonraki ödeme uzaktaysa yüz yeşildir.",
                "Un pago puede estar próximo, vencer hoy, estar vencido o pagado. El color depende del pago pendiente más cercano: más de 7 días verde ☺; de 7 a 4 días amarillo ☻; 3 días o menos rojo ☹. Cualquier vencido es rojo. Si este mes está cubierto y el próximo pago queda lejos, la carita es verde."));
        section(content,"7",local("Общая сводка и сортировка","Summary and sorting","Genel özet ve sıralama","Resumen y ordenación"),local(
                "В «Мои платежи» первой показывается «Общая сводка»: общий остаток долга, фактически оставшаяся к оплате сумма в текущем месяце, оплаченные в текущем месяце платежи, количество оставшихся платежей в текущем месяце и просрочка. После полной оплаты месяца строка «К оплате в этом месяце» становится 0 ₽. Сумма «Оплачено по графику» сохраняется в истории и не пропадает после досрочного погашения или рефинансирования. Досрочные погашения показываются отдельной строкой и не смешиваются с обычными ежемесячными платежами. Ниже общей сводки находится карточка «Ваша выгода» с общей экономией от досрочных погашений и рефинансирований. Потяните страницу «Мои платежи» вниз, чтобы принудительно перечитать все локальные записи, пересчитать сводку и производные расчёты, очистить уведомления уже оплаченных платежей и заново запланировать актуальные напоминания. Обновление относится к общей модели данных приложения, поэтому следующие открываемые экраны используют уже обновлённые данные. Если на ближайшую дату приходится несколько платежей, строка «Следующий платёж» складывает их все и показывает количество и общую сумму. Отдельно показывается, сколько платежей и на какую общую сумму запланировано на следующий календарный месяц. Под кнопкой сортировки показывается текущий режим сортировки.",
                "My payments shows total debt, this month scheduled paid/remaining and overdue amounts. Early repayments are shown separately from normal monthly installments. The Your savings card is also located here and opens the history of savings from early repayment and refinancing. If several payments share the nearest date, Next payment combines all of them and shows their count and total. A separate line shows the number and total value of payments due in the next calendar month. The current sort mode is shown under the sort button.",
                "Ödemelerim ekranında toplam borç, bu ay ödenecek, ödenen, kalan, gecikmiş ve en yakın ödeme gösterilir. Sıralama düğmesinin altında aktif sıralamanın tam adı görünür. Sayfadan çıkıp tekrar girince sıralama En yakın ödeme olur.",
                "Mis pagos muestra deuda total, importe del mes, pagado, pendiente, vencido y próximo pago. Debajo del botón de ordenación aparece el nombre completo del orden activo. Al salir y volver, se restablece a Pago más próximo."));
        section(content,"8",local("График платежей и архив","Payment schedule and archive","Ödeme planı ve arşiv","Calendario de pagos y archivo"),local(
                "В подробностях оплаченные старые платежи скрыты по умолчанию. Нажмите «Архив» справа от заголовка графика, чтобы показать их; при выходе из записи архив снова скрывается. Неоплаченные просроченные платежи не прячутся. Нажмите на строку платежа, чтобы увидеть основной долг, проценты и остаток после платежа. Если платёж был случайно отмечен оплаченным, откройте «Архив» графика, раскройте этот платёж и нажмите «Вернуть платёж».",
                "In details, old paid payments are hidden by default. Tap Archive beside the schedule title to show them; leaving the item hides them again. Unpaid overdue installments stay visible. Tap a payment row to see principal, interest and balance after payment. If an installment was marked paid by mistake, open the schedule Archive, expand that installment and tap Restore payment.",
                "Ayrıntılarda eski ödenmiş taksitler varsayılan olarak gizlidir. Plan başlığının yanındaki Arşiv düğmesiyle gösterin; kayıttan çıkınca tekrar gizlenir. Ödenmemiş gecikmiş taksitler gizlenmez. Anapara, faiz ve ödeme sonrası bakiyeyi görmek için satıra dokunun.",
                "En los detalles, los pagos antiguos ya pagados se ocultan por defecto. Pulsa Archivo junto al título del calendario para mostrarlos; al salir volverán a ocultarse. Los vencidos sin pagar permanecen visibles. Pulsa una fila para ver capital, intereses y saldo posterior."));
        section(content,"9",local("Изменение суммы и фактическая оплата","Changing a scheduled amount and actual payment","Plan tutarı ve gerçek ödeme","Cambiar importe previsto y pago real"),local(
                "В раскрытом платеже можно изменить плановую сумму: только этот платёж или этот и все следующие; отдельно выбирается, менять ли архивные платежи. Для фактической оплаты укажите сумму, дату и при необходимости штраф/пеню. После отметки сегодняшнего платежа постоянное уведомление в шторке закрывается.",
                "An expanded payment lets you change the planned amount for this payment or this and following payments, with a separate choice for archived payments. For an actual payment enter amount, date and optional penalty. Marking today's payment paid also closes its ongoing notification.",
                "Açılan ödeme satırında planlanan tutarı yalnızca bu ödeme veya bu ve sonraki ödemeler için değiştirebilirsiniz; arşiv ayrı seçilir. Gerçek ödeme için tutar, tarih ve gerekirse ceza girin. Bugünkü ödeme işaretlenince kalıcı bildirim de kapanır.",
                "En una fila desplegada puedes cambiar el importe previsto solo para este pago o para este y los siguientes, con una opción aparte para archivados. Para el pago real indica importe, fecha y penalización opcional. Al marcar pagado el de hoy también se cierra su notificación persistente."));
        section(content,"10",local("Досрочное погашение","Early repayment","Erken ödeme","Amortización anticipada"),local(
                "Откройте отдельную страницу «Досрочное погашение», введите сумму и дату. Кнопка «Вся сумма» подставляет весь расчётный остаток на выбранную дату для полного закрытия кредита. Слева и справа сравниваются уменьшение ежемесячного платежа и сокращение срока. Проценты считаются помесячно от фактического остатка долга; последний платёж корректируется до точной суммы остатка, поэтому для сокращения срока нельзя просто умножать обычный платёж на количество месяцев. Если досрочное погашение приходится на дату обычного платежа, приложение ориентируется на отметку «Оплачено», а не на часы: если банк уже списал обычный платёж, сначала отметьте его оплаченным в графике. Можно поправить рассчитанные платёж и срок по данным банка — экономия пересчитается по введённым значениям. Зелёная рамка показывает более выгодный по процентам вариант, красная — меньшую экономию. Приложение ничего не выбирает за вас.",
                "Open Early repayment and enter amount and date. Reducing the payment and reducing the term are compared side by side. If early repayment falls on the regular due date, payment status is used rather than the clock time; mark the ordinary installment Paid first if the bank has already charged it. You may edit calculated values to match bank figures. Green marks greater interest savings and red less. The app does not choose for you.",
                "Erken ödeme sayfasında tutar ve tarihi girin. Aylık ödeme azaltma ve vade kısaltma yan yana karşılaştırılır. Banka verilerine göre değerleri düzeltebilirsiniz. Yeşil daha fazla faiz tasarrufunu, kırmızı daha azını gösterir. Uygulama sizin yerinize seçim yapmaz.",
                "Abre Amortización anticipada e introduce importe y fecha. Se comparan reducir cuota y reducir plazo. Puedes corregir los valores según el banco. Verde indica mayor ahorro de intereses y rojo menor. La app no decide por ti."));
        section(content,"11",local("Рефинансирование","Refinancing","Yeniden finansman","Refinanciación"),local(
                "На отдельной странице укажите новую ставку, срок, комиссию, страховку, дату и при необходимости новую сумму кредита. Приложение сравнит текущий кредит и рефинансирование, включая комиссию, страховку, тип платежей и точную сумму будущих выплат. Для дифференцированного кредита учитывается уменьшающийся платёж, а не первый платёж, умноженный на весь срок. Зелёная рамка показывает более выгодный расчёт, но окончательное решение всегда выбирает пользователь.",
                "Enter new rate, term, commission, insurance, date and, if needed, a new loan amount. The app compares the current loan with refinancing including extra costs and future payments. Green marks the cheaper estimate, but the final choice is yours.",
                "Yeni faiz, vade, komisyon, sigorta, tarih ve gerekirse yeni kredi tutarını girin. Uygulama mevcut kredi ile yeniden finansmanı ek masraflar ve gelecekteki ödemeler dahil karşılaştırır. Yeşil daha avantajlı hesabı gösterir, son karar kullanıcıya aittir.",
                "Introduce nuevo interés, plazo, comisión, seguro, fecha y, si hace falta, nuevo importe. La app compara el préstamo actual con la refinanciación, incluidos gastos y pagos futuros. Verde marca el cálculo más favorable, pero la decisión es del usuario."));
        section(content,"12",local("История, архив и корзина","History, archive and trash","Geçmiş, arşiv ve çöp kutusu","Historial, archivo y papelera"),local(
                "История изменений сохраняет создание записи, редактирование, фактические оплаты, изменения графика, досрочные погашения, рефинансирования и перемещения. Архив предназначен для неактивных записей. После переноса записи в архив она перестаёт участвовать в активной сводке и активной «Вашей выгоде», но её история, исходные данные и накопленная выгода сохраняются в архиве. Корзина хранит удалённые записи до 30 дней и позволяет восстановить их.",
                "Change history records creation, edits, actual payments, schedule changes, early repayments, refinancing and moves. Archive holds inactive items. Trash keeps deleted items for up to 30 days and allows restoration.",
                "Değişiklik geçmişi oluşturma, düzenleme, gerçek ödemeler, plan değişiklikleri, erken ödeme, yeniden finansman ve taşımaları kaydeder. Arşiv pasif kayıtlar içindir. Çöp kutusu silinen kayıtları 30 güne kadar tutar ve geri yüklemeye izin verir.",
                "El historial guarda creación, ediciones, pagos reales, cambios del calendario, amortizaciones anticipadas, refinanciaciones y movimientos. Archivo contiene registros inactivos. Papelera conserva eliminados hasta 30 días y permite restaurarlos."));
        section(content,"13",local("Безопасность","Security","Güvenlik","Seguridad"),local(
                "В Настройки → Безопасность можно выбрать PIN приложения, пароль приложения, графический ключ приложения или системный PIN/пароль/графический ключ телефона. Для PIN/пароля есть показ и скрытие введённых символов. Смена способа и полное отключение защиты всегда требуют подтверждения текущей защиты. Биометрию можно включить отдельно; если отпечаток пальца или другая биометрия ещё не добавлены на телефоне, сначала добавьте их в настройках устройства, затем вернитесь сюда.",
                "Settings → Security offers an app PIN, app password, app pattern, or the phone system PIN/password/pattern. PIN/password entry can be shown or hidden. Changing the method or disabling protection always requires the current protection first. Biometrics can be enabled separately; if no fingerprint or other biometric is enrolled, add it in device settings first and then return here.",
                "Ayarlar → Güvenlik bölümünde uygulama PIN'i, uygulama parolası veya cihaz PIN/parolası seçilebilir. Uygulama parolası/PIN'i için gösterme seçeneği vardır ve mevcut yöntem ekranda görünür. Yöntemi değiştirmeden önce eski uygulama bilgisi veya cihazın sistem doğrulaması gerekir. Destekleniyorsa biyometri ayrıca açılabilir.",
                "En Ajustes → Seguridad puedes elegir PIN de la app, contraseña de la app o PIN/contraseña del dispositivo. Los secretos de la app tienen opción para mostrarlos y la pantalla indica el método actual. Para cambiarlo primero se exige la protección actual: secreto de la app o autenticación del dispositivo. La biometría puede activarse por separado si es compatible."));
        section(content,"14",local("Резервная копия и полный сброс","Backup and full reset","Yedekleme ve tam sıfırlama","Copia de seguridad y restablecimiento"),local(
                "Резервная копия .fcalc включает записи, статусы оплат, историю, напоминания, настройки и профиль. Полный сброс удаляет данные приложения, но не файлы резервных копий на телефоне. Если защита включена, перед двумя обычными подтверждениями сброса приложение сначала попросит текущий PIN/пароль приложения или системную защиту устройства.",
                "A .fcalc backup includes records, payment statuses, history, reminders, settings and profile. Full reset deletes app data but not backup files on the phone. If protection is enabled, the app first requires the current app secret or device credential before the normal two reset confirmations.",
                ".fcalc yedeği kayıtları, ödeme durumlarını, geçmişi, hatırlatmaları, ayarları ve profili içerir. Tam sıfırlama uygulama verilerini siler ancak telefondaki yedek dosyalarını silmez. Koruma açıksa iki normal onaydan önce mevcut uygulama bilgisi veya cihaz doğrulaması gerekir.",
                "La copia .fcalc incluye registros, estados, historial, recordatorios, ajustes y perfil. El restablecimiento elimina los datos de la app, no los archivos de copia del teléfono. Si hay protección, antes de las dos confirmaciones normales se exige el secreto actual de la app o la autenticación del dispositivo."));
        section(content,"15",local("Обратная связь и оценка","Feedback and rating","Geri bildirim ve değerlendirme","Comentarios y valoración"),local(
                "В «О приложении» находятся «Сообщить об ошибке», «Предложить улучшение», «Мои обращения» и «Оценить приложение». К обращению можно временно прикрепить до 5 фото или видео. Приложение не копирует эти файлы в свою память и не хранит их после отправки: в истории остаются только название, дата, тип и текст обращения. После нескольких реально оплаченных платежей приложение может изредка ненавязчиво предложить поставить оценку; «Не сейчас» откладывает предложение.",
                "About contains Report a bug, Suggest an improvement, My requests and Rate the app. Up to 5 photos or videos may be attached temporarily. The app does not copy or retain those files after sending; history keeps only the request title, date, type and text. After several actual paid installments the app may occasionally ask for a rating; Not now postpones it.",
                "Uygulama hakkında bölümünde hata bildirme, iyileştirme önerme, başvuru geçmişi ve uygulamayı değerlendirme seçenekleri vardır. Fotoğraf ve videolar yalnızca gönderim sırasında geçici olarak kullanılır ve uygulamada saklanmaz; geçmişte yalnızca metin kalır.",
                "En Acerca de puedes informar de errores, proponer mejoras, ver tus solicitudes y valorar la app. Las fotos y vídeos se usan solo temporalmente para el envío y no se guardan; el historial conserva solo texto."));
        section(content,"16",local("Личный кабинет","Personal cabinet","Kişisel hesap","Área personal"),local(
                "В меню доступен «Личный кабинет». Здесь можно указать ФИО, ежемесячный доход, другие обязательные платежи, известный официальный рейтинг БКИ, количество кредитных заявок и отказов. Денежные поля форматируются пробелами, а долговая нагрузка и кредитное здоровье пересчитываются сразу при вводе. Нажмите «Сохранить», чтобы записать введённые данные. Потяните страницу вниз, чтобы перечитать платежи, архив и просрочки и обновить показатели. Приложение автоматически показывает активные и архивные кредиты, долг, платёжную дисциплину, просрочки и долговую нагрузку. На их основе рассчитывается внутренняя оценка «Кредитное здоровье» 0–100. Это не официальный рейтинг БКИ. Возле показателей есть ⓘ с объяснением расчёта и источника данных.",
                "Personal cabinet lets you enter monthly income, other mandatory payments, a known official bureau score, applications and rejections. The app combines these with recorded loans, payment discipline, overdue items and debt burden to calculate an internal Credit health score from 0 to 100. It is not an official credit-bureau score. Tap ⓘ beside metrics for details.",
                "Kişisel hesap gelir, diğer zorunlu ödemeler, bilinen resmi puan, başvurular ve retler için alanlar içerir. Uygulama kayıtlı krediler ve ödeme disiplininden 0–100 dahili bir kredi sağlığı puanı üretir. Bu resmi kredi bürosu puanı değildir.",
                "El Área personal permite indicar ingresos, otros pagos obligatorios, una puntuación oficial conocida, solicitudes y rechazos. La app combina estos datos con los préstamos y la disciplina de pago para una evaluación interna de 0 a 100. No es una puntuación oficial del buró."));
        section(content,"17",local("Подсказки и предупреждение о точности","Hints and estimate notice","İpuçları ve tahmini değer uyarısı","Ayudas y aviso de estimación"),local(
                "При первом входе в «Мои платежи» показывается обязательное информационное предупреждение: расчёты ориентировочные и могут отличаться от данных банка. При первом входе в «Личный кабинет» отдельно показывается предупреждение, что кредитное здоровье, платёжная дисциплина и долговая нагрузка — внутренние ориентировочные показатели, а не официальный рейтинг БКИ или решение банка. После кнопки «Понятно, продолжить» каждое предупреждение появляется снова только после очистки данных/полного сброса. В «Мои платежи» и «Личном кабинете» возле основных показателей есть ⓘ: нажмите, чтобы узнать, что означает показатель, как он считается и какие данные в него входят.",
                "The first visit to My payments shows a required notice that calculations are estimates and may differ from bank data. After I understand, continue it is not shown again unless app data is cleared. My payments and Personal cabinet use ⓘ beside key metrics to explain meaning, calculation and included data.",
                "Ödemelerim ilk açıldığında hesapların tahmini olduğunu belirten bir uyarı gösterilir. Ana göstergelerdeki ⓘ simgesi anlamı ve hesaplamayı açıklar.",
                "La primera entrada en Mis pagos muestra un aviso de que los cálculos son aproximados. El icono ⓘ junto a los indicadores explica su significado y cálculo."));
        section(content,"!",local("Точность расчётов","Calculation accuracy","Hesap doğruluğu","Precisión de los cálculos"),local(
                "Банк может использовать другие правила округления, даты начисления процентов, комиссии, страховки и условия договора. Поэтому приложение является помощником для расчёта и контроля, а фактические данные банка можно вручную внести в график.",
                "Banks may use different rounding, interest dates, fees, insurance and contract rules. The app is a calculation and tracking assistant; actual bank figures can be entered manually into the schedule.",
                "Bankalar farklı yuvarlama, faiz tarihleri, komisyon, sigorta ve sözleşme kuralları kullanabilir. Bu nedenle uygulama hesaplama ve takip yardımcısıdır; bankanın gerçek verileri plana elle girilebilir.",
                "Los bancos pueden usar otros redondeos, fechas de intereses, comisiones, seguros y condiciones. Por eso la app es una ayuda de cálculo y control; los datos reales del banco pueden introducirse manualmente en el calendario."));

        ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,bars.top,0,0);scroll.setPadding(0,0,0,bars.bottom+dp(8));return insets;});return root;}

    private String local(String ru,String en,String tr,String es){String l=AppPreferences.getLanguage(this);if("en".equals(l))return en;if("tr".equals(l))return tr;if("es".equals(l))return es;return ru;}
    private void section(LinearLayout parent,String number,String title,String body){MaterialCardView card=new MaterialCardView(this);card.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));card.setRadius(dp(16));card.setStrokeColor(ContextCompat.getColor(this,R.color.border));card.setStrokeWidth(dp(1));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(14),dp(16),dp(14));card.addView(box);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);box.addView(row);TextView badge=text(number,14,R.color.white,true);badge.setGravity(Gravity.CENTER);badge.setBackgroundResource(R.drawable.circle_primary);row.addView(badge,new LinearLayout.LayoutParams(dp(36),dp(36)));TextView t=text(title,18,R.color.text_main,true);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1f);tp.setMargins(dp(12),0,0,0);row.addView(t,tp);TextView b=text(body,14,R.color.text_secondary,false);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(10),0,0);box.addView(b,bp);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(10));parent.addView(card,cp);}
    private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,c));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
