package com.example.creditcalculator;

import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.GravityCompat;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.drawerlayout.widget.DrawerLayout;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.switchmaterial.SwitchMaterial;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;

public class MainActivity extends AppCompatActivity {
    public static final String EXTRA_SHOW_CALCULATORS = "show_calculators";
    private enum Mode { CREDIT, MORTGAGE, AUTO, INSTALLMENT, DEPOSIT }

    private DrawerLayout drawer;
    private LinearLayout mainColumn, drawerView, content, formBox;
    private ScrollView scroll;
    private MaterialCardView formCard, resultCard;
    private MaterialButton creditBtn, mortgageBtn, autoBtn, installmentBtn, depositBtn;
    private TextInputEditText amountInput, downInput, termInput, rateInput, insuranceInput;
    private Spinner termSpinner, paymentTypeSpinner;
    private SwitchMaterial insuranceSwitch, capitalizationSwitch;
    private TextView calcTitle, calcSubtitle, rLabel1,rLabel2,rLabel3,rValue1,rValue2,rValue3, benefitValue;
    private MaterialCardView benefitCard;
    private ImageView drawerAvatar; private TextView drawerAvatarFallback, drawerName;
    private Mode mode;
    private String loadedLanguage;
    private double lastPrincipal,lastBase,lastDown,lastInsurance,lastRate,lastPayment;
    private int lastMonths; private boolean lastInsuranceFinanced=true; private String lastPaymentType=ReminderScheduler.PAYMENT_ANNUITY;

    @Override protected void attachBaseContext(Context newBase){super.attachBaseContext(AppPreferences.wrapLocale(newBase));}
    @Override public void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);if(b==null&&!getIntent().getBooleanExtra(EXTRA_SHOW_CALCULATORS,false)){Intent payments=new Intent(this,PaymentsActivity.class);startActivity(payments);finish();overridePendingTransition(0,0);return;}loadedLanguage=AppPreferences.getLanguage(this);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);setContentView(build());refreshProfile();refreshBenefit();}
    @Override protected void onResume(){super.onResume();if(loadedLanguage!=null&&!loadedLanguage.equals(AppPreferences.getLanguage(this))){recreate();return;}if(mainColumn!=null)UiUtils.applyBackground(this,mainColumn);refreshProfile();refreshBenefit();}

    private View build(){drawer=new DrawerLayout(this);drawer.setFitsSystemWindows(false);FrameLayout frame=new FrameLayout(this);drawer.addView(frame,new DrawerLayout.LayoutParams(-1,-1));mainColumn=new LinearLayout(this);mainColumn.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,mainColumn);frame.addView(mainColumn,new FrameLayout.LayoutParams(-1,-1));mainColumn.addView(topBar(),new LinearLayout.LayoutParams(-1,dp(56)));scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);mainColumn.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(20),dp(20),dp(30));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));
        content.addView(text(AppPreferences.tr(this,"Калькуляторы","Calculators"),28,R.color.text_main,true));TextView sub=text(AppPreferences.tr(this,"Выберите нужный раздел","Choose a calculator"),15,R.color.text_secondary,false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(6),0,dp(18));content.addView(sub,sp);
        
        creditBtn=calcButton(AppPreferences.tr(this,"Кредит","Loan"));mortgageBtn=calcButton(AppPreferences.tr(this,"Ипотека","Mortgage"));autoBtn=calcButton(AppPreferences.tr(this,"Автокредит","Auto loan"));installmentBtn=calcButton(AppPreferences.tr(this,"Рассрочка","Installment"));depositBtn=calcButton(AppPreferences.tr(this,"Вклад","Deposit"));content.addView(creditBtn,calcParams());content.addView(mortgageBtn,calcParams());content.addView(autoBtn,calcParams());content.addView(installmentBtn,calcParams());content.addView(depositBtn,calcParams());
        creditBtn.setOnClickListener(v->select(Mode.CREDIT));mortgageBtn.setOnClickListener(v->select(Mode.MORTGAGE));autoBtn.setOnClickListener(v->select(Mode.AUTO));installmentBtn.setOnClickListener(v->select(Mode.INSTALLMENT));depositBtn.setOnClickListener(v->select(Mode.DEPOSIT));
        formCard=card();formBox=new LinearLayout(this);formBox.setOrientation(LinearLayout.VERTICAL);formBox.setPadding(dp(18),dp(18),dp(18),dp(18));formCard.addView(formBox);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,-2);fp.setMargins(0,dp(10),0,0);content.addView(formCard,fp);formCard.setVisibility(View.GONE);
        resultCard=resultCard();LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(16),0,dp(20));content.addView(resultCard,rp);resultCard.setVisibility(View.GONE);
        drawerView=NavigationPanel.build(this,drawer,NavigationPanel.PAGE_CALCULATORS);DrawerLayout.LayoutParams dpv=new DrawerLayout.LayoutParams(NavigationPanel.drawerWidth(this),-1);dpv.gravity=GravityCompat.START;drawer.addView(drawerView,dpv);ViewCompat.setOnApplyWindowInsetsListener(drawer,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());Insets ime=insets.getInsets(WindowInsetsCompat.Type.ime());frame.setPadding(0,bars.top,0,bars.bottom);drawerView.setPadding(0,bars.top,0,bars.bottom);scroll.setPadding(0,0,0,Math.max(dp(88),ime.bottom+dp(16)));UiUtils.ensureFocusedFieldVisible(scroll);return insets;});return drawer;}

    private MaterialCardView buildBenefitCard(){MaterialCardView c=card();c.setClickable(true);c.setOnClickListener(v->startActivity(new Intent(this,BenefitHistoryActivity.class)));LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(14),dp(18),dp(14));c.addView(b);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(AppPreferences.tr(this,"Ваша выгода","Your savings"),18,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));row.addView(text("›",28,R.color.primary,true));b.addView(row);benefitValue=text("0 ₽",24,R.color.success,true);b.addView(benefitValue);b.addView(text(AppPreferences.tr(this,"Досрочные погашения и рефинансирование","Early repayments and refinancing"),12,R.color.text_secondary,false));return c;}
    private void refreshBenefit(){if(benefitValue==null)return;double total=ReminderScheduler.totalBenefit(this);benefitValue.setText(FormatUtils.money(this,total));benefitValue.setTextColor(ContextCompat.getColor(this,total>=0?R.color.success:R.color.danger));}

    private View topBar(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(4),0,dp(12),0);b.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));TextView menu=text("☰",30,R.color.white,false);menu.setGravity(Gravity.CENTER);menu.setClickable(true);menu.setOnClickListener(v->drawer.openDrawer(GravityCompat.START));b.addView(menu,new LinearLayout.LayoutParams(dp(60),dp(56)));TextView t=text(AppPreferences.tr(this,"Финансовый калькулятор","Financial calculator"),20,R.color.white,true);t.setGravity(Gravity.CENTER_VERTICAL);b.addView(t,new LinearLayout.LayoutParams(0,-1,1f));return b;}

    private LinearLayout buildDrawer(){LinearLayout d=new LinearLayout(this);d.setOrientation(LinearLayout.VERTICAL);d.setBackgroundColor(ContextCompat.getColor(this,R.color.card_background));LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(20),dp(20),dp(12),dp(20));h.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));d.addView(h,new LinearLayout.LayoutParams(-1,dp(168)));FrameLayout av=new FrameLayout(this);h.addView(av,new LinearLayout.LayoutParams(dp(72),dp(72)));drawerAvatarFallback=text("%",40,R.color.white,true);drawerAvatarFallback.setGravity(Gravity.CENTER);drawerAvatarFallback.setBackgroundColor(ContextCompat.getColor(this,R.color.primary_dark));av.addView(drawerAvatarFallback,new FrameLayout.LayoutParams(-1,-1));drawerAvatar=new ImageView(this);drawerAvatar.setScaleType(ImageView.ScaleType.CENTER_CROP);drawerAvatar.setVisibility(View.GONE);av.addView(drawerAvatar,new FrameLayout.LayoutParams(-1,-1));drawerName=text(AppPreferences.tr(this,"Финансовый\nкалькулятор","Financial\ncalculator"),22,R.color.white,false);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,-2,1f);np.setMargins(dp(16),0,dp(4),0);h.addView(drawerName,np);TextView edit=text("✎",25,R.color.white,false);edit.setGravity(Gravity.CENTER);edit.setClickable(true);edit.setOnClickListener(v->{drawer.closeDrawer(GravityCompat.START);startActivity(new Intent(this,ProfileActivity.class));});h.addView(edit,new LinearLayout.LayoutParams(dp(48),dp(48)));
        TextView calculators=drawerItem("▶   "+AppPreferences.tr(this,"Калькуляторы","Calculators"));calculators.setOnClickListener(v->{drawer.closeDrawer(GravityCompat.START);scroll.smoothScrollTo(0,0);});d.addView(calculators);TextView earlyPay=drawerItem("↗   "+AppPreferences.tr(this,"Досрочный платёж","Early payment"));earlyPay.setOnClickListener(v->openPage(EarlyPaymentAdvisorActivity.class));d.addView(earlyPay);TextView payments=drawerItem("☷   "+AppPreferences.tr(this,"Мои платежи","My payments"));payments.setOnClickListener(v->openPage(PaymentsActivity.class));d.addView(payments);TextView cabinet=drawerItem("▤   "+AppPreferences.tr(this,"Личный кабинет","Personal cabinet"));cabinet.setOnClickListener(v->openPage(PersonalCabinetActivity.class));d.addView(cabinet);TextView archive=drawerItem("▣   "+AppPreferences.tr(this,"Архив","Archive"));archive.setOnClickListener(v->openPage(ArchiveActivity.class));d.addView(archive);TextView trash=drawerItem("⌫   "+AppPreferences.tr(this,"Корзина","Trash"));trash.setOnClickListener(v->openPage(TrashActivity.class));d.addView(trash);TextView settings=drawerItem("⚙   "+AppPreferences.tr(this,"Настройки","Settings"));settings.setOnClickListener(v->openPage(SettingsActivity.class));d.addView(settings);View div=new View(this);div.setBackgroundColor(ContextCompat.getColor(this,R.color.border));d.addView(div,new LinearLayout.LayoutParams(-1,dp(1)));TextView about=drawerItem("ⓘ   "+AppPreferences.tr(this,"О приложении","About"));about.setOnClickListener(v->openPage(AboutActivity.class));d.addView(about);TextView exit=drawerItem("↪   "+AppPreferences.tr(this,"Выход","Exit"));exit.setOnClickListener(v->finishAffinity());d.addView(exit);return d;}
    private void openPage(Class<?> c){drawer.closeDrawer(GravityCompat.START);startActivity(new Intent(this,c));}
    private void refreshProfile(){if(drawerName==null)return;String n=AppPreferences.getProfileName(this);drawerName.setText(n.isEmpty()?AppPreferences.tr(this,"Финансовый\nкалькулятор","Financial\ncalculator"):n);String a=AppPreferences.getAvatarUri(this);if(a==null||a.isEmpty()){drawerAvatar.setVisibility(View.GONE);drawerAvatarFallback.setVisibility(View.VISIBLE);}else try{drawerAvatar.setImageURI(Uri.parse(a));drawerAvatar.setVisibility(View.VISIBLE);drawerAvatarFallback.setVisibility(View.GONE);}catch(Exception e){drawerAvatar.setVisibility(View.GONE);drawerAvatarFallback.setVisibility(View.VISIBLE);}}

    private void select(Mode m){mode=m;resultCard.setVisibility(View.GONE);lastPrincipal=lastBase=lastDown=lastInsurance=lastRate=lastPayment=0;lastMonths=0;lastInsuranceFinanced=true;lastPaymentType=ReminderScheduler.PAYMENT_ANNUITY;buildForm();styleButtons();formCard.setVisibility(View.VISIBLE);formCard.post(()->scroll.smoothScrollTo(0,formCard.getTop()));}
    private void buildForm(){formBox.removeAllViews();calcTitle=text(titleForMode(),23,R.color.text_main,true);formBox.addView(calcTitle);calcSubtitle=text(subtitleForMode(),14,R.color.text_secondary,false);LinearLayout.LayoutParams csp=new LinearLayout.LayoutParams(-1,-2);csp.setMargins(0,dp(4),0,dp(16));formBox.addView(calcSubtitle,csp);
        amountInput=field(iconHint("▣",amountHint()),AppPreferences.tr(this,"Укажите основную сумму по договору. Для ипотеки и автокредита это полная стоимость до вычета первоначального взноса; для вклада — сумма вклада.","Enter the main contract amount. For mortgage and auto loan this is the full price before the down payment; for a deposit it is the deposit amount."));
        if(mode==Mode.MORTGAGE||mode==Mode.AUTO||mode==Mode.INSTALLMENT)downInput=field(iconHint("◩",AppPreferences.tr(this,"Первоначальный взнос, ₽","Down payment, ₽")),AppPreferences.tr(this,"Сумма, которую вы вносите сразу. Она должна быть меньше полной стоимости.","The amount paid upfront. It must be less than the full price."));else downInput=null;
        termInput=termField(AppPreferences.tr(this,"Введите срок и выберите справа месяцы или годы. От срока зависит количество платежей и итоговая переплата.","Enter the term and choose months or years on the right. The term affects the number of payments and total overpayment."));
        if(mode!=Mode.INSTALLMENT)rateInput=field(iconHint("%",AppPreferences.tr(this,"Ставка, % годовых","Interest rate, % per year")),AppPreferences.tr(this,"Введите годовую процентную ставку из условий банка.","Enter the annual interest rate from the bank terms."));else rateInput=null;
        if(mode!=Mode.DEPOSIT){insuranceInput=field(iconHint("◇",AppPreferences.tr(this,"Страховка, ₽","Insurance, ₽")),AppPreferences.tr(this,"Введите стоимость страховки. Она всегда учитывается в общей переплате. Переключатель ниже определяет только способ оплаты: включить её в сумму кредита или оплатить отдельно.","Enter the insurance cost. It is always included in total overpayment. The switch below only controls how it is paid: financed with the loan or paid separately."));insuranceSwitch=new SwitchMaterial(this);insuranceSwitch.setText(mode==Mode.INSTALLMENT?AppPreferences.tr(this,"Включить страховку в рассрочку","Include insurance in installment"):AppPreferences.tr(this,"Включить страховку в сумму кредита","Include insurance in financed amount"));insuranceSwitch.setTextColor(ContextCompat.getColor(this,R.color.text_main));insuranceSwitch.setTextSize(14);insuranceSwitch.setChecked(true);LinearLayout.LayoutParams isp=new LinearLayout.LayoutParams(-1,-2);isp.setMargins(0,dp(-4),0,dp(12));formBox.addView(insuranceSwitch,isp);}else{insuranceInput=null;insuranceSwitch=null;}
        if(mode==Mode.CREDIT||mode==Mode.MORTGAGE||mode==Mode.AUTO){TextView pl=text(AppPreferences.tr(this,"Тип платежей","Payment type")+"  ⓘ",14,R.color.text_secondary,true);pl.setClickable(true);pl.setOnClickListener(v->showInfo(AppPreferences.tr(this,"Тип платежей","Payment type"),AppPreferences.tr(this,"Аннуитетный платёж примерно одинаковый каждый месяц. При дифференцированном основной долг гасится равными частями, поэтому платёж постепенно уменьшается.","Annuity payments are roughly equal each month. With differential payments the principal is repaid in equal portions, so the payment gradually decreases.")));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(6));formBox.addView(pl,lp);paymentTypeSpinner=new Spinner(this);UiUtils.styleSpinner(this,paymentTypeSpinner);paymentTypeSpinner.setAdapter(UiUtils.spinnerAdapter(this,new String[]{AppPreferences.tr(this,"Аннуитетный","Annuity"),AppPreferences.tr(this,"Дифференцированный","Differential")}));formBox.addView(paymentTypeSpinner,new LinearLayout.LayoutParams(-1,dp(56)));}else paymentTypeSpinner=null;
        if(mode==Mode.DEPOSIT){capitalizationSwitch=new SwitchMaterial(this);capitalizationSwitch.setText(AppPreferences.tr(this,"Ежемесячная капитализация процентов","Monthly interest capitalization"));capitalizationSwitch.setTextColor(ContextCompat.getColor(this,R.color.text_main));capitalizationSwitch.setTextSize(14);formBox.addView(capitalizationSwitch,new LinearLayout.LayoutParams(-1,dp(54)));}else capitalizationSwitch=null;
        MaterialButton calc=new MaterialButton(this);calc.setText(AppPreferences.tr(this,"Рассчитать","Calculate"));calc.setAllCaps(false);calc.setTextSize(17);calc.setTextColor(Color.WHITE);calc.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));calc.setCornerRadius(dp(14));calc.setOnClickListener(v->calculate());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(56));bp.setMargins(0,dp(12),0,0);formBox.addView(calc,bp);}

    private String titleForMode(){if(mode==Mode.MORTGAGE)return AppPreferences.tr(this,"Ипотека","Mortgage");if(mode==Mode.AUTO)return AppPreferences.tr(this,"Автокредит","Auto loan");if(mode==Mode.INSTALLMENT)return AppPreferences.tr(this,"Рассрочка","Installment");if(mode==Mode.DEPOSIT)return AppPreferences.tr(this,"Вклад","Deposit");return AppPreferences.tr(this,"Кредит","Loan");}
    private String subtitleForMode(){if(mode==Mode.DEPOSIT)return AppPreferences.tr(this,"Рассчитайте доход и итоговую сумму вклада","Calculate deposit income and final amount");if(mode==Mode.INSTALLMENT)return AppPreferences.tr(this,"Рассчитайте платёж рассрочки с учётом страховки","Calculate installment payments including insurance");return AppPreferences.tr(this,"Рассчитайте платёж, проценты и переплату","Calculate payment, interest and overpayment");}
    private String amountHint(){if(mode==Mode.MORTGAGE)return AppPreferences.tr(this,"Стоимость жилья, ₽","Property price, ₽");if(mode==Mode.AUTO)return AppPreferences.tr(this,"Стоимость автомобиля, ₽","Car price, ₽");if(mode==Mode.INSTALLMENT)return AppPreferences.tr(this,"Стоимость покупки, ₽","Purchase price, ₽");if(mode==Mode.DEPOSIT)return AppPreferences.tr(this,"Сумма вклада, ₽","Deposit amount, ₽");return AppPreferences.tr(this,"Сумма кредита, ₽","Loan amount, ₽");}
    private String iconHint(String icon,String h){return icon+"   "+h;}

    private TextInputEditText field(String hint,String help){String label=cleanFieldLabel(hint);formBox.addView(infoLabelRow(label,help));TextInputLayout l=inputLayout(null);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));formBox.addView(l,p);TextInputEditText e=new TextInputEditText(this);e.setHint(label);e.setHintTextColor(ContextCompat.getColor(this,R.color.text_secondary));e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setSingleLine(true);e.setMinHeight(dp(58));e.setTextColor(ContextCompat.getColor(this,R.color.text_main));l.addView(e,new TextInputLayout.LayoutParams(-1,-2));if(hint.contains("₽"))UiUtils.attachMoneyFormatting(e);UiUtils.keepFieldVisibleOnFocus(scroll,e);e.addTextChangedListener(new SimpleWatcher(()->{}));return e;}
    private TextInputEditText termField(String help){formBox.addView(infoLabelRow(AppPreferences.tr(this,"Срок","Term"),help));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,0,0,dp(12));formBox.addView(row,rp);TextInputLayout l=inputLayout(null);TextInputEditText e=new TextInputEditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setSingleLine(true);e.setMinHeight(dp(58));e.setTextColor(ContextCompat.getColor(this,R.color.text_main));l.addView(e,new TextInputLayout.LayoutParams(-1,-2));row.addView(l,new LinearLayout.LayoutParams(0,-2,1f));termSpinner=new Spinner(this);UiUtils.styleSpinner(this,termSpinner);termSpinner.setAdapter(UiUtils.spinnerAdapter(this,new String[]{UiUtils.termUnit(this,1,false),UiUtils.termUnit(this,1,true)}));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(dp(128),dp(58));up.setMargins(dp(8),0,0,0);row.addView(termSpinner,up);UiUtils.keepFieldVisibleOnFocus(scroll,e);e.addTextChangedListener(new SimpleWatcher(()->updateTermSpinner(e)));return e;}
    private void updateTermSpinner(TextInputEditText e){int v=1;try{v=Math.max(1,Integer.parseInt(raw(e)));}catch(Exception ignored){}int s=termSpinner.getSelectedItemPosition();termSpinner.setAdapter(UiUtils.spinnerAdapter(this,new String[]{UiUtils.termUnit(this,v,false),UiUtils.termUnit(this,v,true)}));termSpinner.setSelection(s);}
        private LinearLayout infoLabelRow(String title,String message){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);TextView label=text(title,14,R.color.text_secondary,true);row.addView(label,new LinearLayout.LayoutParams(0,-2,1f));TextView icon=text("ⓘ",21,R.color.primary,true);icon.setGravity(Gravity.CENTER);icon.setClickable(true);icon.setOnClickListener(v->showInfo(title,message));row.addView(icon,new LinearLayout.LayoutParams(dp(40),dp(40)));return row;}
    private String cleanFieldLabel(String h){return h==null?"":h.replaceFirst("^\\S+\\s+","");}
    private void showInfo(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton(AppPreferences.tr(this,"Понятно","OK"),null).show();}
    private TextInputLayout inputLayout(String hint){TextInputLayout l=new TextInputLayout(this);if(hint!=null&&!hint.isEmpty())l.setHint(hint);l.setBoxBackgroundMode(TextInputLayout.BOX_BACKGROUND_OUTLINE);l.setBoxBackgroundColor(ContextCompat.getColor(this,R.color.card_background));l.setBoxStrokeColor(ContextCompat.getColor(this,R.color.primary));l.setHintTextColor(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.text_secondary)));l.setBoxCornerRadii(dp(14),dp(14),dp(14),dp(14));return l;}

    private void calculate(){try{if(mode==null)throw new IllegalArgumentException();double base=positive(amountInput),down=downInput==null?0:nonNeg(downInput),ins=insuranceInput==null?0:nonNeg(insuranceInput);if(down>=base&&mode!=Mode.DEPOSIT)throw new IllegalArgumentException();int months=termMonths();double rate=rateInput==null?0:nonNeg(rateInput);boolean financed=insuranceSwitch!=null&&insuranceSwitch.isChecked();double principal=mode==Mode.DEPOSIT?base:base-down+(financed?ins:0);lastBase=base;lastDown=down;lastInsurance=ins;lastInsuranceFinanced=financed;lastPrincipal=principal;lastRate=rate;lastMonths=months;lastPaymentType=paymentTypeSpinner!=null&&paymentTypeSpinner.getSelectedItemPosition()==1?ReminderScheduler.PAYMENT_DIFFERENTIAL:ReminderScheduler.PAYMENT_ANNUITY;
            if(mode==Mode.DEPOSIT){double finalAmount=capitalizationSwitch!=null&&capitalizationSwitch.isChecked()?FinanceMath.monthlyCompoundDepositFinal(principal,months,rate):principal+FinanceMath.simpleDepositInterest(principal,months,rate);show(AppPreferences.tr(this,"Доход по вкладу","Deposit income"),finalAmount-principal,AppPreferences.tr(this,"Итоговая сумма","Final amount"),finalAmount,AppPreferences.tr(this,"Капитализация","Capitalization"),capitalizationSwitch!=null&&capitalizationSwitch.isChecked()?AppPreferences.tr(this,"Ежемесячная","Monthly"):AppPreferences.tr(this,"Без капитализации","No capitalization"));lastPayment=0;return;}
            if(mode==Mode.INSTALLMENT){double payment=principal/months;double overpayment=FinanceMath.totalOverpayment(0,ins,0);lastPayment=payment;showMoney(AppPreferences.tr(this,"Ежемесячный платёж","Monthly payment"),payment,AppPreferences.tr(this,"Общая переплата (страховка)","Total overpayment (insurance)"),overpayment,AppPreferences.tr(this,"Общая стоимость","Total cost"),base+ins);return;}
            if(ReminderScheduler.PAYMENT_DIFFERENTIAL.equals(lastPaymentType)){double first=ReminderScheduler.differentialFirstPayment(principal,months,rate),last=ReminderScheduler.differentialLastPayment(principal,months,rate),interest=ReminderScheduler.differentialTotalInterest(principal,months,rate),overpayment=FinanceMath.totalOverpayment(interest,ins,0);lastPayment=first;showMoney(AppPreferences.tr(this,"Первый платёж","First payment"),first,AppPreferences.tr(this,"Последний платёж","Last payment"),last,AppPreferences.tr(this,"Общая переплата (проценты + страховка)","Total overpayment (interest + insurance)"),overpayment);}else{double payment=ReminderScheduler.annuity(principal,months,rate),total=payment*months,interest=total-principal,overpayment=FinanceMath.totalOverpayment(interest,ins,0),borrowerPayments=total+(financed?0:ins);lastPayment=payment;showMoney(AppPreferences.tr(this,"Ежемесячный платёж","Monthly payment"),payment,AppPreferences.tr(this,"Общая сумма выплат с учётом страховки","Total payments incl. insurance"),borrowerPayments,AppPreferences.tr(this,"Общая переплата (проценты + страховка)","Total overpayment (interest + insurance)"),overpayment);}
        }catch(Exception e){resultCard.setVisibility(View.GONE);Toast.makeText(this,AppPreferences.tr(this,"Заполните все поля правильно","Check all entered values"),Toast.LENGTH_SHORT).show();}}

    private int termMonths(){int v=Integer.parseInt(raw(termInput));if(v<=0)throw new IllegalArgumentException();return termSpinner.getSelectedItemPosition()==1?v*12:v;}
    private double positive(TextInputEditText e){double v=Double.parseDouble(clean(raw(e)));if(v<=0)throw new IllegalArgumentException();return v;}private double nonNeg(TextInputEditText e){String s=clean(raw(e));if(s.isEmpty())return 0;double v=Double.parseDouble(s);if(v<0)throw new IllegalArgumentException();return v;}private String raw(TextInputEditText e){return e==null||e.getText()==null?"":e.getText().toString();}private String clean(String s){return s.trim().replace(" ","").replace("\u00A0","").replace("\u202F","").replace(',','.');}
    private void showMoney(String l1,double v1,String l2,double v2,String l3,double v3){rLabel1.setText(l1);rValue1.setText(FormatUtils.money(this,v1));rLabel2.setText(l2);rValue2.setText(FormatUtils.money(this,v2));rLabel3.setText(l3);rValue3.setText(FormatUtils.money(this,v3));resultCard.setVisibility(View.VISIBLE);}
    private void show(String l1,double v1,String l2,double v2,String l3,String v3){rLabel1.setText(l1);rValue1.setText(FormatUtils.money(this,v1));rLabel2.setText(l2);rValue2.setText(FormatUtils.money(this,v2));rLabel3.setText(l3);rValue3.setText(v3);resultCard.setVisibility(View.VISIBLE);}
    private MaterialCardView resultCard(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.result_card));c.setRadius(dp(18));LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),dp(18),dp(20),dp(18));c.addView(b);b.addView(text(AppPreferences.tr(this,"Результат","Result"),18,R.color.white,true));rLabel1=text("",14,R.color.result_secondary,false);rValue1=text("",26,R.color.white,true);rLabel2=text("",14,R.color.result_secondary,false);rValue2=text("",20,R.color.white,true);rLabel3=text("",14,R.color.result_secondary,false);rValue3=text("",20,R.color.white,true);LinearLayout.LayoutParams gap=new LinearLayout.LayoutParams(-1,-2);gap.setMargins(0,dp(12),0,0);b.addView(rLabel1,gap);b.addView(rValue1);b.addView(rLabel2,gap);b.addView(rValue2);b.addView(rLabel3,gap);b.addView(rValue3);return c;}

    private void openAdd(){Intent i=new Intent(this,AddReminderActivity.class);if(mode!=null)i.putExtra(AddReminderActivity.EXTRA_TYPE,typeForMode());if(lastPrincipal>0){i.putExtra(AddReminderActivity.EXTRA_PRINCIPAL,lastPrincipal);i.putExtra(AddReminderActivity.EXTRA_BASE_AMOUNT,lastBase);i.putExtra(AddReminderActivity.EXTRA_DOWN_PAYMENT,lastDown);i.putExtra(AddReminderActivity.EXTRA_INSURANCE,lastInsurance);i.putExtra(AddReminderActivity.EXTRA_INSURANCE_FINANCED,lastInsuranceFinanced);i.putExtra(AddReminderActivity.EXTRA_RATE,lastRate);i.putExtra(AddReminderActivity.EXTRA_PAYMENT_TYPE,lastPaymentType);}if(lastMonths>0)i.putExtra(AddReminderActivity.EXTRA_MONTHS,lastMonths);if(lastPayment>0)i.putExtra(AddReminderActivity.EXTRA_PAYMENT,lastPayment);startActivity(i);}
    private String typeForMode(){if(mode==Mode.MORTGAGE)return ReminderScheduler.TYPE_MORTGAGE;if(mode==Mode.AUTO)return ReminderScheduler.TYPE_AUTO;if(mode==Mode.INSTALLMENT)return ReminderScheduler.TYPE_INSTALLMENT;if(mode==Mode.DEPOSIT)return ReminderScheduler.TYPE_DEPOSIT;return ReminderScheduler.TYPE_CREDIT;}

    private void styleButtons(){style(creditBtn,mode==Mode.CREDIT);style(mortgageBtn,mode==Mode.MORTGAGE);style(autoBtn,mode==Mode.AUTO);style(installmentBtn,mode==Mode.INSTALLMENT);style(depositBtn,mode==Mode.DEPOSIT);}private void style(MaterialButton b,boolean on){int p=ContextCompat.getColor(this,R.color.primary);b.setBackgroundTintList(ColorStateList.valueOf(on?p:ContextCompat.getColor(this,R.color.card_background)));b.setTextColor(on?Color.WHITE:p);b.setStrokeColor(ColorStateList.valueOf(p));b.setStrokeWidth(dp(1));}
    private MaterialButton calcButton(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setTextSize(17);b.setTextColor(ContextCompat.getColor(this,R.color.primary));b.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.card_background)));b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));b.setStrokeWidth(dp(1));b.setCornerRadius(dp(15));return b;}private LinearLayout.LayoutParams calcParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,0,0,dp(14));return p;}
    private MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));c.setRadius(dp(20));c.setStrokeColor(ContextCompat.getColor(this,R.color.border));c.setStrokeWidth(dp(1));return c;}private TextView drawerItem(String s){TextView t=text(s,18,R.color.text_main,false);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(24),0,dp(16),0);t.setClickable(true);t.setBackgroundResource(android.R.drawable.list_selector_background);t.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(58)));return t;}private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,c));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    @android.annotation.SuppressLint("MissingSuperCall")
    @Override public void onBackPressed(){if(drawer!=null&&drawer.isDrawerOpen(GravityCompat.START))drawer.closeDrawer(GravityCompat.START);else super.onBackPressed();}
    private static class SimpleWatcher implements TextWatcher{private final Runnable r;SimpleWatcher(Runnable r){this.r=r;}public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){}public void afterTextChanged(Editable e){if(r!=null)r.run();}}
}
