package com.example.creditcalculator;

import android.app.DatePickerDialog;
import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.PopupMenu;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;

import java.util.Calendar;

public class PaymentDetailsActivity extends AppCompatActivity {
    public static final String EXTRA_REMINDER_ID = "reminder_id";
    private ReminderScheduler.PaymentReminder reminder;
    private long renderedUpdatedAt;
    private boolean showArchive;
    private int expandedIndex = -1;
    private LinearLayout scheduleContainer;
    private TextView archiveToggle;

    @Override protected void attachBaseContext(Context newBase){super.attachBaseContext(AppPreferences.wrapLocale(newBase));}
    @Override public void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);long id=getIntent().getLongExtra(EXTRA_REMINDER_ID,-1);reminder=ReminderScheduler.findById(this,id);if(reminder==null){Toast.makeText(this,AppPreferences.tr(this,"Запись не найдена","Item not found"),Toast.LENGTH_SHORT).show();finish();return;}renderedUpdatedAt=reminder.updatedAt;setContentView(build());}
    @Override protected void onResume(){super.onResume();if(reminder==null)return;ReminderScheduler.PaymentReminder r=ReminderScheduler.findById(this,reminder.id);if(r==null){finish();return;}if(renderedUpdatedAt!=r.updatedAt){reminder=r;renderedUpdatedAt=r.updatedAt;recreate();}}

    private View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(4),0,dp(6),0);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));TextView back=top("‹",34);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView bt=top(reminder.title,20);bt.setTypeface(null,android.graphics.Typeface.BOLD);bt.setGravity(Gravity.CENTER_VERTICAL);bar.addView(bt,new LinearLayout.LayoutParams(0,-1,1f));TextView more=top("⋮",28);more.setOnClickListener(v->topMenu(more));bar.addView(more,new LinearLayout.LayoutParams(dp(52),dp(56)));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(22),dp(20),dp(32));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));content.addView(text(FormatUtils.typeLabel(this,reminder.type),14,R.color.primary,true));LinearLayout titleRow=new LinearLayout(this);titleRow.setOrientation(LinearLayout.HORIZONTAL);titleRow.setGravity(Gravity.CENTER_VERTICAL);content.addView(titleRow,new LinearLayout.LayoutParams(-1,-2));titleRow.addView(text(reminder.title,28,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));if(!ReminderScheduler.STATUS_TRASH.equals(reminder.status)){TextView edit=text("✎",25,R.color.primary,false);edit.setGravity(Gravity.CENTER);edit.setClickable(true);edit.setOnClickListener(v->editRecord());titleRow.addView(edit,new LinearLayout.LayoutParams(dp(48),dp(48)));}TextView created=text(AppPreferences.tr(this,"Создано: ","Created: ")+FormatUtils.date(this,reminder.createdAt),12,R.color.text_secondary,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(16));content.addView(created,cp);
        content.addView(mainSummary());
        if(!isDeposit()){content.addView(conditionsCard(),section());content.addView(interestCard(),section());if(!ReminderScheduler.benefits(reminder).isEmpty())content.addView(benefitCard(),section());if(ReminderScheduler.STATUS_ACTIVE.equals(reminder.status))content.addView(actionsCard(),section());}
        if(isDeposit()){TextView st=text(AppPreferences.tr(this,"Срок вклада","Deposit term"),22,R.color.text_main,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(24),0,dp(10));content.addView(st,sp);content.addView(depositCard());}else{LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.HORIZONTAL);header.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.setMargins(0,dp(24),0,dp(10));content.addView(header,hp);header.addView(text(AppPreferences.tr(this,"График платежей","Payment schedule"),22,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));archiveToggle=text(AppPreferences.tr(this,"Архив","Archive"),14,R.color.primary,true);archiveToggle.setGravity(Gravity.CENTER);archiveToggle.setPadding(dp(10),dp(8),dp(4),dp(8));archiveToggle.setClickable(true);archiveToggle.setOnClickListener(v->{showArchive=!showArchive;expandedIndex=-1;renderSchedule();});header.addView(archiveToggle);scheduleContainer=new LinearLayout(this);scheduleContainer.setOrientation(LinearLayout.VERTICAL);content.addView(scheduleContainer);renderSchedule();}
        if(!ReminderScheduler.STATUS_TRASH.equals(reminder.status)){MaterialButton del=outline(AppPreferences.tr(this,"Удалить в корзину","Move to trash"),R.color.danger);del.setOnClickListener(v->confirmDelete());LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(-1,dp(54));dpv.setMargins(0,dp(20),0,0);content.addView(del,dpv);}ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());Insets ime=insets.getInsets(WindowInsetsCompat.Type.ime());v.setPadding(0,bars.top,0,0);scroll.setPadding(0,0,0,Math.max(bars.bottom,ime.bottom)+dp(8));UiUtils.ensureFocusedFieldVisible(scroll);return insets;});return root;}

    private View mainSummary(){MaterialCardView card=resultCard();LinearLayout b=cardBox(card);if(isDeposit()){bigLabelValue(b,AppPreferences.tr(this,"Сумма вклада","Deposit amount"),FormatUtils.money(this,reminder.principal));addSummary(b,AppPreferences.tr(this,"Ставка","Interest rate"),rate(reminder.annualRate)+"%");addSummary(b,AppPreferences.tr(this,"Ожидаемый доход","Expected income"),FormatUtils.money(this,ReminderScheduler.depositExpectedIncome(reminder)));addSummary(b,AppPreferences.tr(this,"Итого к получению","Expected total"),FormatUtils.money(this,ReminderScheduler.depositFinalAmount(reminder)));return card;}
        bigLabelValue(b,AppPreferences.tr(this,"Остаток долга","Remaining debt"),FormatUtils.money(this,ReminderScheduler.remainingDebt(reminder)));int next=ReminderScheduler.nextPaymentIndex(reminder);if(next>=0){ReminderScheduler.PaymentParts p=ReminderScheduler.paymentParts(reminder,next);int color=statusColor(next);TextView label=text(AppPreferences.tr(this,"Ближайший платёж","Next payment"),13,R.color.result_secondary,false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(12),0,dp(2));b.addView(label,lp);TextView value=text(FormatUtils.money(this,p.amount),24,R.color.white,true);value.setTextColor(ContextCompat.getColor(this,color));b.addView(value);addSummary(b,AppPreferences.tr(this,"Дата платежа","Payment date"),FormatUtils.date(this,p.dueDate));}else addSummary(b,AppPreferences.tr(this,"Ближайший платёж","Next payment"),AppPreferences.tr(this,"Все платежи оплачены","All payments paid"));addSummary(b,AppPreferences.tr(this,"Ставка","Interest rate"),rate(reminder.annualRate)+"%");int remaining=Math.max(0,reminder.months-ReminderScheduler.paidPaymentCount(reminder));long end=ReminderScheduler.buildDueDate(reminder,Math.max(0,reminder.months-1)).getTimeInMillis();addSummary(b,AppPreferences.tr(this,"Осталось платить","Remaining term"),remaining+AppPreferences.tr(this," мес. / до "," mo. / until ")+FormatUtils.date(this,end));return card;}

    private View conditionsCard(){MaterialCardView card=basicCard();LinearLayout b=cardBox(card);b.addView(text(AppPreferences.tr(this,"Условия кредита","Loan terms"),19,R.color.text_main,true));summaryDark(b,AppPreferences.tr(this,"Исходная сумма","Original amount"),FormatUtils.money(this,reminder.baseAmount));if(reminder.downPayment>0)summaryDark(b,AppPreferences.tr(this,"Первоначальный взнос","Down payment"),FormatUtils.money(this,reminder.downPayment));if(reminder.insurance>0){summaryDark(b,AppPreferences.tr(this,"Страховка","Insurance"),FormatUtils.money(this,reminder.insurance));summaryDark(b,AppPreferences.tr(this,"Страховка включена в кредит","Insurance financed"),reminder.insuranceFinanced?AppPreferences.tr(this,"Да","Yes"):AppPreferences.tr(this,"Нет, оплачена отдельно","No, paid separately"));}summaryDark(b,AppPreferences.tr(this,"Сумма кредита с учётом страховки","Financed amount"),FormatUtils.money(this,reminder.principal));summaryDark(b,AppPreferences.tr(this,"Первоначальный срок","Original term"),UiUtils.termText(this,reminder.months));summaryDark(b,AppPreferences.tr(this,"Первый платёж","First payment"),FormatUtils.date(this,reminder.firstPaymentMillis));if(!ReminderScheduler.TYPE_INSTALLMENT.equals(ReminderScheduler.normalizeType(reminder.type)))summaryDark(b,AppPreferences.tr(this,"Тип платежей","Payment type"),FormatUtils.paymentTypeLabel(this,reminder.paymentType));summaryDark(b,AppPreferences.tr(this,"Время напоминания","Reminder time"),String.format(java.util.Locale.US,"%02d:%02d",reminder.reminderHour,reminder.reminderMinute));return card;}

    private View interestCard(){MaterialCardView card=basicCard();LinearLayout b=cardBox(card);b.addView(text(AppPreferences.tr(this,"Проценты и переплата","Interest and overpayment"),19,R.color.text_main,true));summaryDark(b,AppPreferences.tr(this,"Общая переплата","Total interest"),FormatUtils.money(this,ReminderScheduler.totalInterest(reminder)));summaryDark(b,AppPreferences.tr(this,"Уже выплачено процентов","Interest already paid"),FormatUtils.money(this,ReminderScheduler.paidInterest(reminder)));summaryDark(b,AppPreferences.tr(this,"Осталось выплатить процентов","Interest remaining"),FormatUtils.money(this,ReminderScheduler.remainingInterest(reminder)));if(ReminderScheduler.totalPenalties(reminder)>0)summaryDark(b,AppPreferences.tr(this,"Штрафы / пени","Penalties"),FormatUtils.money(this,ReminderScheduler.totalPenalties(reminder)));double progress=ReminderScheduler.progress(reminder);TextView pc=text(AppPreferences.tr(this,"Выплачено","Paid")+" "+Math.round(progress*100)+"%",15,R.color.text_main,true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,-2);pp.setMargins(0,dp(14),0,dp(6));b.addView(pc,pp);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(1000);pb.setProgress((int)Math.round(progress*1000));pb.setProgressTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.primary)));b.addView(pb,new LinearLayout.LayoutParams(-1,dp(10)));TextView ptxt=text(AppPreferences.tr(this,"Погашено основного долга: ","Principal repaid: ")+FormatUtils.money(this,ReminderScheduler.paidPrincipal(reminder))+AppPreferences.tr(this," из "," of ")+FormatUtils.money(this,ReminderScheduler.progressOriginalPrincipal(reminder)),12,R.color.text_secondary,false);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.setMargins(0,dp(7),0,0);b.addView(ptxt,tp);return card;}

    private View benefitCard(){MaterialCardView card=basicCard();card.setClickable(true);card.setOnClickListener(v->{Intent i=new Intent(this,BenefitHistoryActivity.class);i.putExtra(BenefitHistoryActivity.EXTRA_REMINDER_ID,reminder.id);startActivity(i);});LinearLayout b=cardBox(card);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(text(AppPreferences.tr(this,"Выгода от изменений","Savings from changes"),19,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));head.addView(text("›",26,R.color.primary,true));b.addView(head);double saved=ReminderScheduler.totalBenefit(reminder);TextView sum=text(AppPreferences.tr(this,"Сэкономлено: ","Estimated saved: ")+FormatUtils.money(this,saved),21,saved>=0?R.color.success:R.color.danger,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(10),0,0);b.addView(sum,sp);int early=ReminderScheduler.historyCount(reminder,ReminderScheduler.HISTORY_EARLY),refi=ReminderScheduler.historyCount(reminder,ReminderScheduler.HISTORY_REFINANCE);b.addView(text(AppPreferences.tr(this,"Досрочных погашений: ","Early repayments: ")+early+" · "+AppPreferences.tr(this,"Рефинансирований: ","Refinancing actions: ")+refi,13,R.color.text_secondary,false));double denominator=Math.max(0,saved)+ReminderScheduler.remainingInterest(reminder);int pct=denominator<=.01?0:(int)Math.round(Math.max(0,saved)/denominator*100);TextView label=text(AppPreferences.tr(this,"Снижение будущей переплаты: ","Future interest reduced: ")+pct+"%",13,R.color.text_secondary,true);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(12),0,dp(6));b.addView(label,lp);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress(Math.max(0,Math.min(100,pct)));pb.setProgressTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.success)));b.addView(pb,new LinearLayout.LayoutParams(-1,dp(9)));return card;}

    private View actionsCard(){MaterialCardView card=basicCard();LinearLayout b=cardBox(card);b.addView(text(AppPreferences.tr(this,"Изменить условия кредита","Loan actions"),18,R.color.text_main,true));MaterialButton early=outline(AppPreferences.tr(this,"Досрочное погашение","Early repayment"),R.color.primary);early.setOnClickListener(v->{Intent i=new Intent(this,EarlyRepaymentActivity.class);i.putExtra(EXTRA_REMINDER_ID,reminder.id);startActivity(i);});LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(52));ep.setMargins(0,dp(12),0,0);b.addView(early,ep);if(!ReminderScheduler.TYPE_INSTALLMENT.equals(ReminderScheduler.normalizeType(reminder.type))){MaterialButton ref=outline(AppPreferences.tr(this,"Рефинансирование","Refinancing"),R.color.primary);ref.setOnClickListener(v->{Intent i=new Intent(this,RefinanceActivity.class);i.putExtra(EXTRA_REMINDER_ID,reminder.id);startActivity(i);});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(52));rp.setMargins(0,dp(10),0,0);b.addView(ref,rp);}return card;}

    private void renderSchedule(){if(scheduleContainer==null)return;scheduleContainer.removeAllViews();archiveToggle.setText(showArchive?AppPreferences.tr(this,"Скрыть архив","Hide archive"):AppPreferences.tr(this,"Архив","Archive"));int shown=0;for(int i=0;i<reminder.months;i++){boolean pastPaid=ReminderScheduler.isPaid(reminder,i)&&ReminderScheduler.buildDueDate(reminder,i).getTimeInMillis()<System.currentTimeMillis();if(pastPaid&&!showArchive)continue;scheduleContainer.addView(scheduleRow(i));shown++;}if(shown==0){TextView empty=text(AppPreferences.tr(this,"Архивных платежей нет","No archived payments"),14,R.color.text_secondary,false);empty.setPadding(0,dp(12),0,dp(12));scheduleContainer.addView(empty);}}
    private View scheduleRow(int index){ReminderScheduler.PaymentParts p=ReminderScheduler.paymentParts(reminder,index);String status=ReminderScheduler.paymentStatus(reminder,index);int color=statusColor(index);MaterialCardView card=basicCard();card.setStrokeColor(ContextCompat.getColor(this,color));card.setClickable(true);card.setOnClickListener(v->{expandedIndex=expandedIndex==index?-1:index;renderSchedule();});LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));card.addView(box);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);box.addView(row);TextView num=text(String.valueOf(index+1),15,color,true);num.setGravity(Gravity.CENTER);num.setBackgroundResource(index==ReminderScheduler.nextPaymentIndex(reminder)?R.drawable.circle_primary:R.drawable.circle_soft);row.addView(num,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout middle=new LinearLayout(this);middle.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,-2,1f);mp.setMargins(dp(12),0,dp(8),0);row.addView(middle,mp);middle.addView(text(FormatUtils.date(this,p.dueDate),16,R.color.text_main,true));String label="paid".equals(status)?AppPreferences.tr(this,"Оплачен","Paid"):"overdue".equals(status)?AppPreferences.tr(this,"Просрочен","Overdue"):"today".equals(status)?AppPreferences.tr(this,"Сегодня","Today"):AppPreferences.tr(this,"Предстоящий","Upcoming");TextView sv=text(label,12,color,true);middle.addView(sv);TextView amount=text(FormatUtils.money(this,p.amount),15,R.color.primary,true);amount.setClickable(true);row.addView(amount);
        if(expandedIndex==index){View div=new View(this);div.setBackgroundColor(ContextCompat.getColor(this,R.color.border));LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(-1,dp(1));dpv.setMargins(0,dp(12),0,dp(10));box.addView(div,dpv);detailLine(box,AppPreferences.tr(this,"В погашение основного долга","Principal"),p.principalPart);detailLine(box,AppPreferences.tr(this,"Проценты","Interest"),p.interestPart);detailLine(box,AppPreferences.tr(this,"Остаток долга после платежа","Balance after payment"),p.balanceAfter);if(ReminderScheduler.paidAmount(reminder,index)>0)detailLine(box,AppPreferences.tr(this,"Фактически оплачено","Actually paid"),ReminderScheduler.paidAmount(reminder,index));if(ReminderScheduler.paidAt(reminder,index)>0)summaryDark(box,AppPreferences.tr(this,"Дата оплаты","Payment date"),FormatUtils.date(this,ReminderScheduler.paidAt(reminder,index)));if(ReminderScheduler.penalty(reminder,index)>0)detailLine(box,AppPreferences.tr(this,"Штраф / пеня","Penalty"),ReminderScheduler.penalty(reminder,index));LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(10),0,0);box.addView(buttons,bp);MaterialButton edit=mini(AppPreferences.tr(this,"Изменить сумму","Change amount"));edit.setOnClickListener(v->{v.getParent().requestDisallowInterceptTouchEvent(true);editAmount(index);});buttons.addView(edit,new LinearLayout.LayoutParams(0,dp(46),1f));MaterialButton paid=mini(ReminderScheduler.isPaid(reminder,index)?AppPreferences.tr(this,"Изменить оплату","Edit payment"):AppPreferences.tr(this,"Платёж оплачен","Payment paid"));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(46),1f);pp.setMargins(dp(8),0,0,0);buttons.addView(paid,pp);paid.setOnClickListener(v->markPaidDialog(index));}
        LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(8));card.setLayoutParams(cp);return card;}
    private int statusColor(int index){if(ReminderScheduler.isPaid(reminder,index))return R.color.success;if(ReminderScheduler.isOverdue(reminder,index)||ReminderScheduler.isToday(reminder,index))return R.color.danger;long days=daysUntil(ReminderScheduler.buildDueDate(reminder,index).getTimeInMillis());if(days<=3)return R.color.danger;if(days<=7)return R.color.warning;return R.color.success;}
    private long daysUntil(long dueMillis){Calendar a=Calendar.getInstance();a.set(Calendar.HOUR_OF_DAY,0);a.set(Calendar.MINUTE,0);a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);Calendar b=Calendar.getInstance();b.setTimeInMillis(dueMillis);b.set(Calendar.HOUR_OF_DAY,0);b.set(Calendar.MINUTE,0);b.set(Calendar.SECOND,0);b.set(Calendar.MILLISECOND,0);return (b.getTimeInMillis()-a.getTimeInMillis())/(24L*60L*60L*1000L);}

    private void editAmount(int index){EditText e=input(AppPreferences.tr(this,"Новая плановая сумма, ₽","New planned amount, ₽"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setText(String.format(java.util.Locale.US,"%.2f",ReminderScheduler.paymentAmount(reminder,index)).replace('.',','));new AlertDialog.Builder(this).setTitle(AppPreferences.tr(this,"Изменить сумму","Change amount")).setView(e).setNegativeButton(AppPreferences.tr(this,"Отмена","Cancel"),null).setPositiveButton(AppPreferences.tr(this,"Продолжить","Continue"),(d,w)->{try{double value=parse(e.getText().toString());chooseAmountScope(index,value);}catch(Exception ex){Toast.makeText(this,AppPreferences.tr(this,"Проверьте сумму","Check the amount"),Toast.LENGTH_SHORT).show();}}).show();}
    private void chooseAmountScope(int index,double value){String[] opts={AppPreferences.tr(this,"Только к этому платежу","Only this payment"),AppPreferences.tr(this,"К этому и всем следующим","This and all following")};new AlertDialog.Builder(this).setTitle(AppPreferences.tr(this,"К каким платежам применить изменение?","Which payments should be changed?")).setItems(opts,(d,which)->askArchiveScope(index,value,which==1)).show();}
    private void askArchiveScope(int index,double value,boolean following){new AlertDialog.Builder(this).setTitle(AppPreferences.tr(this,"Изменить также архивные платежи?","Change archived payments too?")).setMessage(AppPreferences.tr(this,"Фактически оплаченная сумма не изменится — изменяется только плановый график.","Actual paid amounts will not change; only the planned schedule is updated.")).setNegativeButton(AppPreferences.tr(this,"Нет, оставить архив без изменений","No, leave archive unchanged"),(d,w)->applyAmount(index,value,following,false)).setPositiveButton(AppPreferences.tr(this,"Да, применить и к архивным","Yes, include archived"),(d,w)->applyAmount(index,value,following,true)).show();}
    private void applyAmount(int index,double value,boolean following,boolean archive){ReminderScheduler.changePlannedAmount(this,reminder.id,index,value,following,archive);refresh();}

    private void markPaidDialog(int index){Calendar paidDate=Calendar.getInstance();if(ReminderScheduler.paidAt(reminder,index)>0)paidDate.setTimeInMillis(ReminderScheduler.paidAt(reminder,index));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(4),dp(20),0);EditText amount=input(AppPreferences.tr(this,"Фактически оплачено, ₽","Actually paid, ₽"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);amount.setText(String.format(java.util.Locale.US,"%.2f",ReminderScheduler.paidAmount(reminder,index)>0?ReminderScheduler.paidAmount(reminder,index):ReminderScheduler.paymentAmount(reminder,index)).replace('.',','));UiUtils.attachMoneyFormatting(amount);box.addView(amount,new LinearLayout.LayoutParams(-1,dp(58)));EditText date=input(AppPreferences.tr(this,"Дата оплаты","Payment date"),InputType.TYPE_NULL);date.setFocusable(false);date.setClickable(true);date.setText(FormatUtils.date(this,paidDate.getTimeInMillis()));date.setOnClickListener(v->new DatePickerDialog(this,(x,y,m,d)->{paidDate.set(y,m,d,12,0,0);date.setText(FormatUtils.date(this,paidDate.getTimeInMillis()));},paidDate.get(Calendar.YEAR),paidDate.get(Calendar.MONTH),paidDate.get(Calendar.DAY_OF_MONTH)).show());box.addView(date,new LinearLayout.LayoutParams(-1,dp(58)));EditText penalty=input(AppPreferences.tr(this,"Штраф / пеня, ₽","Penalty, ₽"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(ReminderScheduler.penalty(reminder,index)>0)penalty.setText(String.valueOf(ReminderScheduler.penalty(reminder,index)));UiUtils.attachMoneyFormatting(penalty);box.addView(penalty,new LinearLayout.LayoutParams(-1,dp(58)));AlertDialog.Builder builder=new AlertDialog.Builder(this).setTitle(AppPreferences.tr(this,"Платёж оплачен","Payment paid")).setView(box).setNegativeButton(AppPreferences.tr(this,"Отмена","Cancel"),null).setPositiveButton(AppPreferences.tr(this,"Применить","Apply"),(d,w)->{try{ReminderScheduler.markPaid(this,reminder.id,index,paidDate.getTimeInMillis(),parse(amount.getText().toString()),parseZero(penalty.getText().toString()));PaymentNotificationHelper.cancel(this,reminder.id,index);refresh();}catch(Exception ex){Toast.makeText(this,AppPreferences.tr(this,"Проверьте введённые данные","Check entered data"),Toast.LENGTH_SHORT).show();}});if(ReminderScheduler.paidAmount(reminder,index)>0)builder.setNeutralButton(AppPreferences.tr(this,"Снять отметку об оплате","Mark unpaid"),(d,w)->{ReminderScheduler.unmarkPaid(this,reminder.id,index);refresh();});builder.show();}

    private View depositCard(){MaterialCardView c=basicCard();LinearLayout b=cardBox(c);Calendar end=ReminderScheduler.buildDueDate(reminder.firstPaymentMillis,reminder.months);summaryDark(b,AppPreferences.tr(this,"Дата открытия","Start date"),FormatUtils.date(this,reminder.firstPaymentMillis));summaryDark(b,AppPreferences.tr(this,"Ожидаемое окончание","Expected maturity"),FormatUtils.date(this,end.getTimeInMillis()));return c;}
    private void topMenu(View anchor){PopupMenu m=new PopupMenu(this,anchor);String hist=AppPreferences.tr(this,"История изменений","Change history");m.getMenu().add(hist);m.setOnMenuItemClickListener(x->{Intent i=new Intent(this,HistoryActivity.class);i.putExtra(HistoryActivity.EXTRA_REMINDER_ID,reminder.id);startActivity(i);return true;});m.show();}private void editRecord(){Intent i=new Intent(this,AddReminderActivity.class);i.putExtra(AddReminderActivity.EXTRA_EDIT_ID,reminder.id);startActivity(i);}
    private void confirmDelete(){new AlertDialog.Builder(this).setTitle(AppPreferences.tr(this,"Переместить в корзину?","Move to trash?")).setMessage(AppPreferences.tr(this,"Запись можно будет восстановить в течение 30 дней.","You can restore the item for 30 days.")).setNegativeButton(AppPreferences.tr(this,"Отмена","Cancel"),null).setPositiveButton(AppPreferences.tr(this,"Удалить","Delete"),(d,w)->{ReminderScheduler.moveToTrash(this,reminder.id);finish();}).show();}
    private void refresh(){ReminderScheduler.PaymentReminder r=ReminderScheduler.findById(this,reminder.id);if(r!=null){reminder=r;renderedUpdatedAt=r.updatedAt;}recreate();}

    private boolean isDeposit(){return ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(reminder.type));}private LinearLayout.LayoutParams section(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(18),0,0);return p;}private MaterialCardView resultCard(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.result_card));c.setRadius(dp(18));return c;}private MaterialCardView basicCard(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));c.setRadius(dp(16));c.setStrokeColor(ContextCompat.getColor(this,R.color.border));c.setStrokeWidth(dp(1));return c;}private LinearLayout cardBox(MaterialCardView c){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(16),dp(18),dp(16));c.addView(b);return b;}
    private void bigLabelValue(LinearLayout b,String l,String v){b.addView(text(l,13,R.color.result_secondary,false));TextView val=text(v,28,R.color.white,true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(3),0,dp(4));b.addView(val,p);}private void addSummary(LinearLayout b,String l,String v){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(8),0,0);b.addView(row,rp);row.addView(text(l,13,R.color.result_secondary,false),new LinearLayout.LayoutParams(0,-2,1f));row.addView(text(v,14,R.color.white,true));}private void summaryDark(LinearLayout b,String l,String v){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(9),0,0);b.addView(row,rp);row.addView(text(l,13,R.color.text_secondary,false),new LinearLayout.LayoutParams(0,-2,1f));TextView value=text(v,14,R.color.text_main,true);value.setGravity(Gravity.END);row.addView(value);}private void detailLine(LinearLayout b,String l,double v){summaryDark(b,l,FormatUtils.money(this,v));}
    private MaterialButton outline(String s,int color){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setTextColor(ContextCompat.getColor(this,color));b.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.card_background)));b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(this,color)));b.setStrokeWidth(dp(1));b.setCornerRadius(dp(14));return b;}private MaterialButton mini(String s){MaterialButton b=outline(s,R.color.primary);b.setTextSize(12);b.setPadding(dp(4),0,dp(4),0);return b;}private EditText input(String h,int type){EditText e=new EditText(this);e.setHint(h);e.setInputType(type);e.setSingleLine(true);e.setTextColor(ContextCompat.getColor(this,R.color.text_main));e.setHintTextColor(ContextCompat.getColor(this,R.color.text_secondary));return e;}private double parse(String s){double d=Double.parseDouble(clean(s));if(d<=0)throw new IllegalArgumentException();return d;}private double parseZero(String s){String c=clean(s);if(c.isEmpty())return 0;double d=Double.parseDouble(c);if(d<0)throw new IllegalArgumentException();return d;}private String clean(String s){return s==null?"":s.replace(" ","").replace("\u00A0","").replace("\u202F","").replace(',','.').trim();}private String rate(double v){return v==Math.floor(v)?String.valueOf((long)v):String.valueOf(v).replace('.',',');}
    private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,color));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
