package com.example.creditcalculator;

import android.app.Dialog;
import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.widget.LinearLayout;
import android.widget.PopupMenu;
import android.widget.ScrollView;
import android.widget.TextView;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.GravityCompat;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class PaymentsActivity extends AppCompatActivity {
    private DrawerLayout drawer;
    private LinearLayout listContainer;
    private SwipeRefreshLayout swipeRefresh;
    private String filterType;
    /** Sorting deliberately resets every time the page is opened. */
    private String sortMode = "nearest";

    @Override protected void attachBaseContext(Context newBase){super.attachBaseContext(AppPreferences.wrapLocale(newBase));}
    @Override public void onCreate(Bundle b){AppPreferences.applyNightMode(this);super.onCreate(b);filterType=AppPreferences.getPaymentsFilter(this);sortMode="nearest";setContentView(build());if(!AppPreferences.isPaymentsDisclaimerAccepted(this))getWindow().getDecorView().post(this::showDisclaimer);}
    @Override protected void onResume(){super.onResume();render();if(AppPreferences.isPaymentsDisclaimerAccepted(this))getWindow().getDecorView().postDelayed(()->RatingHelper.maybePrompt(this),450);}

    private View build(){
        drawer=new DrawerLayout(this);drawer.setFitsSystemWindows(false);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);UiUtils.applyBackground(this,root);drawer.addView(root,new DrawerLayout.LayoutParams(-1,-1));
        LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),0,dp(10),0);bar.setBackgroundColor(ContextCompat.getColor(this,R.color.primary));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(58)));
        TextView back=top("☰",30);back.setOnClickListener(v->showNavigationMenu(back));bar.addView(back,new LinearLayout.LayoutParams(dp(54),dp(54)));
        TextView title=top(AppPreferences.tr(this,"Мои платежи","My payments"),20);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,-1,1f));
        TextView add=top("+",32);add.setOnClickListener(v->startActivity(new Intent(this,AddReminderActivity.class)));bar.addView(add,new LinearLayout.LayoutParams(dp(64),dp(58)));
        swipeRefresh=new SwipeRefreshLayout(this);swipeRefresh.setColorSchemeResources(R.color.primary);root.addView(swipeRefresh,new LinearLayout.LayoutParams(-1,0,1f));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);swipeRefresh.addView(scroll,new SwipeRefreshLayout.LayoutParams(-1,-1));
        listContainer=new LinearLayout(this);listContainer.setOrientation(LinearLayout.VERTICAL);listContainer.setPadding(dp(20),dp(22),dp(20),dp(28));scroll.addView(listContainer,new ScrollView.LayoutParams(-1,-2));swipeRefresh.setOnRefreshListener(this::refreshAllData);
        LinearLayout nav=NavigationPanel.build(this,drawer,NavigationPanel.PAGE_PAYMENTS);DrawerLayout.LayoutParams np=new DrawerLayout.LayoutParams(NavigationPanel.drawerWidth(this),-1);np.gravity=GravityCompat.START;drawer.addView(nav,np);
        ViewCompat.setOnApplyWindowInsetsListener(drawer,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars());root.setPadding(0,bars.top,0,bars.bottom);nav.setPadding(0,bars.top,0,bars.bottom);return insets;});
        return drawer;
    }

    private void render(){listContainer.removeAllViews();listContainer.addView(text(AppPreferences.tr(this,"Мои платежи","My payments"),28,R.color.text_main,true));List<ReminderScheduler.PaymentReminder> all=ReminderScheduler.load(this);listContainer.addView(summary(all));listContainer.addView(benefitSummary(),benefitParams());listContainer.addView(controls(),controlsParams());List<ReminderScheduler.PaymentReminder> shown=filterSort(all);TextView head=text(AppPreferences.tr(this,"Активные записи — ","Active items — ")+shown.size(),19,R.color.text_main,true);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.setMargins(0,dp(18),0,dp(10));listContainer.addView(head,hp);if(shown.isEmpty()){TextView e=text(AppPreferences.tr(this,all.isEmpty()?"Активных записей пока нет. Нажмите +, чтобы добавить первую.":"По выбранному фильтру записей нет.",all.isEmpty()?"No active items yet. Tap + to add one.":"No items match the filter."),16,R.color.text_secondary,false);e.setGravity(Gravity.CENTER);e.setPadding(dp(12),dp(42),dp(12),dp(64));listContainer.addView(e);return;}for(ReminderScheduler.PaymentReminder r:shown)listContainer.addView(paymentCard(r));}

    private void refreshAllData(){
        try {
            ReminderScheduler.refreshAll(this);
            render();
        } finally {
            if(swipeRefresh!=null) swipeRefresh.setRefreshing(false);
        }
    }

    private View benefitSummary(){MaterialCardView c=card();c.setClickable(true);c.setFocusable(true);c.setOnClickListener(v->{Intent i=new Intent(this,BenefitHistoryActivity.class);i.putExtra(BenefitHistoryActivity.EXTRA_ACTIVE_ONLY,true);startActivity(i);});LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(15),dp(18),dp(15));c.addView(b);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);TextView h=text(AppPreferences.tr(this,"Ваша выгода","Your savings"),19,R.color.text_main,true);h.setClickable(true);h.setOnClickListener(v->showInfo(AppPreferences.tr(this,"Ваша выгода","Your savings"),AppPreferences.tr(this,"Здесь учитывается расчётная экономия только по кредитам, которые сейчас активны. Архивные кредиты не входят.","Estimated savings for currently active loans only. Archived loans are excluded.")));row.addView(h,new LinearLayout.LayoutParams(0,-2,1f));row.addView(text("›",28,R.color.primary,true));b.addView(row);double total=ReminderScheduler.totalBenefit(this);b.addView(text(FormatUtils.money(this,total),25,total>=0?R.color.success:R.color.danger,true));TextView early=text(AppPreferences.tr(this,"Досрочно погашено по активным кредитам","Early repaid on active loans")+": "+FormatUtils.money(this,activeEarlyRepaymentTotal())+"  ⓘ",13,R.color.primary,true);early.setClickable(true);early.setOnClickListener(v->showInfo(AppPreferences.tr(this,"Досрочно погашено по активным кредитам","Early repaid on active loans"),AppPreferences.tr(this,"Сумма всех зарегистрированных досрочных погашений за всё время только по кредитам, которые сейчас активны. Досрочные погашения архивных кредитов здесь не показываются.","Lifetime registered early repayments for loans that are currently active only. Early repayments of archived loans are not shown here.")));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,-2);ep.setMargins(0,dp(5),0,0);b.addView(early,ep);b.addView(text(AppPreferences.tr(this,"Досрочные погашения и рефинансирование","Early repayments and refinancing"),13,R.color.text_secondary,false));return c;}
    private double activeEarlyRepaymentTotal(){double total=0;for(ReminderScheduler.PaymentReminder r:ReminderScheduler.load(this))for(ReminderScheduler.BenefitEvent e:ReminderScheduler.benefits(r))if(ReminderScheduler.HISTORY_EARLY.equals(e.type))total+=Math.max(0,e.actionAmount);return total;}
    private LinearLayout.LayoutParams benefitParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(16),0,0);return p;}

    private View controls(){LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);outer.addView(row,new LinearLayout.LayoutParams(-1,-2));MaterialButton filter=small(filterLabel());filter.setOnClickListener(v->showFilter(filter));row.addView(filter,new LinearLayout.LayoutParams(0,dp(48),1f));MaterialButton sort=small(sortButtonLabel());LinearLayout.LayoutParams sr=new LinearLayout.LayoutParams(0,dp(48),1f);sr.setMargins(dp(10),0,0,0);row.addView(sort,sr);sort.setOnClickListener(v->showSort(sort));return outer;}
    private LinearLayout.LayoutParams controlsParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(16),0,0);return p;}
    private MaterialButton small(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setSingleLine(true);b.setTextSize(13);b.setTextColor(ContextCompat.getColor(this,R.color.primary));b.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.card_background)));b.setStrokeColor(ColorStateList.valueOf(ContextCompat.getColor(this,R.color.border)));b.setStrokeWidth(dp(1));b.setCornerRadius(dp(12));return b;}
    private String filterLabel(){String v;if(ReminderScheduler.TYPE_CREDIT.equals(filterType))v=FormatUtils.typeLabel(this,ReminderScheduler.TYPE_CREDIT);else if(ReminderScheduler.TYPE_MORTGAGE.equals(filterType))v=FormatUtils.typeLabel(this,ReminderScheduler.TYPE_MORTGAGE);else if(ReminderScheduler.TYPE_AUTO.equals(filterType))v=FormatUtils.typeLabel(this,ReminderScheduler.TYPE_AUTO);else if(ReminderScheduler.TYPE_INSTALLMENT.equals(filterType))v=FormatUtils.typeLabel(this,ReminderScheduler.TYPE_INSTALLMENT);else if(ReminderScheduler.TYPE_DEPOSIT.equals(filterType))v=FormatUtils.typeLabel(this,ReminderScheduler.TYPE_DEPOSIT);else v=AppPreferences.tr(this,"Все","All");return AppPreferences.tr(this,"Фильтр: ","Filter: ")+v;}
    private String sortName(String m){if("created_new".equals(m))return AppPreferences.tr(this,"дата создания — новые сначала","created — newest first");if("created_old".equals(m))return AppPreferences.tr(this,"дата создания — старые сначала","created — oldest first");if("name_asc".equals(m))return AppPreferences.tr(this,"название А–Я","name A–Z");if("name_desc".equals(m))return AppPreferences.tr(this,"название Я–А","name Z–A");if("debt_desc".equals(m))return AppPreferences.tr(this,"остаток долга — по убыванию","remaining debt — highest first");if("debt_asc".equals(m))return AppPreferences.tr(this,"остаток долга — по возрастанию","remaining debt — lowest first");if("payment_desc".equals(m))return AppPreferences.tr(this,"ежемесячный платёж — по убыванию","monthly payment — highest first");if("payment_asc".equals(m))return AppPreferences.tr(this,"ежемесячный платёж — по возрастанию","monthly payment — lowest first");if("rate_desc".equals(m))return AppPreferences.tr(this,"ставка — по убыванию","rate — highest first");if("rate_asc".equals(m))return AppPreferences.tr(this,"ставка — по возрастанию","rate — lowest first");if("type".equals(m))return AppPreferences.tr(this,"по типу","by type");return AppPreferences.tr(this,"ближайший платёж","nearest payment");}
    private String sortButtonLabel(){if("created_new".equals(sortMode))return AppPreferences.tr(this,"Дата: новые","Date: newest");if("created_old".equals(sortMode))return AppPreferences.tr(this,"Дата: старые","Date: oldest");if("name_asc".equals(sortMode))return AppPreferences.tr(this,"Название А–Я","Name A–Z");if("name_desc".equals(sortMode))return AppPreferences.tr(this,"Название Я–А","Name Z–A");if("debt_desc".equals(sortMode))return AppPreferences.tr(this,"Остаток долга ↓","Debt ↓");if("debt_asc".equals(sortMode))return AppPreferences.tr(this,"Остаток долга ↑","Debt ↑");if("payment_desc".equals(sortMode))return AppPreferences.tr(this,"Платёж ↓","Payment ↓");if("payment_asc".equals(sortMode))return AppPreferences.tr(this,"Платёж ↑","Payment ↑");if("rate_desc".equals(sortMode))return AppPreferences.tr(this,"Ставка ↓","Rate ↓");if("rate_asc".equals(sortMode))return AppPreferences.tr(this,"Ставка ↑","Rate ↑");if("type".equals(sortMode))return AppPreferences.tr(this,"По типу","By type");return AppPreferences.tr(this,"Ближайший платёж","Nearest payment");}
    private void showFilter(View a){PopupMenu m=new PopupMenu(this,a);addFilter(m,AppPreferences.tr(this,"Все","All"),"all");addFilter(m,FormatUtils.typeLabel(this,ReminderScheduler.TYPE_CREDIT),ReminderScheduler.TYPE_CREDIT);addFilter(m,FormatUtils.typeLabel(this,ReminderScheduler.TYPE_MORTGAGE),ReminderScheduler.TYPE_MORTGAGE);addFilter(m,FormatUtils.typeLabel(this,ReminderScheduler.TYPE_AUTO),ReminderScheduler.TYPE_AUTO);addFilter(m,FormatUtils.typeLabel(this,ReminderScheduler.TYPE_INSTALLMENT),ReminderScheduler.TYPE_INSTALLMENT);addFilter(m,FormatUtils.typeLabel(this,ReminderScheduler.TYPE_DEPOSIT),ReminderScheduler.TYPE_DEPOSIT);m.show();}
    private void addFilter(PopupMenu m,String label,String value){m.getMenu().add(label).setOnMenuItemClickListener(x->{filterType=value;AppPreferences.setPaymentsFilter(this,value);render();return true;});}
    private void showSort(View a){PopupMenu m=new PopupMenu(this,a);addSort(m,AppPreferences.tr(this,"Ближайший платёж","Nearest payment"),"nearest");addSort(m,AppPreferences.tr(this,"Дата создания — новые сначала","Created — newest first"),"created_new");addSort(m,AppPreferences.tr(this,"Дата создания — старые сначала","Created — oldest first"),"created_old");addSort(m,AppPreferences.tr(this,"Название А–Я","Name A–Z"),"name_asc");addSort(m,AppPreferences.tr(this,"Название Я–А","Name Z–A"),"name_desc");addSort(m,AppPreferences.tr(this,"Остаток долга — больше сначала","Debt — highest first"),"debt_desc");addSort(m,AppPreferences.tr(this,"Остаток долга — меньше сначала","Debt — lowest first"),"debt_asc");addSort(m,AppPreferences.tr(this,"Ежемесячный платёж — больше сначала","Payment — highest first"),"payment_desc");addSort(m,AppPreferences.tr(this,"Ежемесячный платёж — меньше сначала","Payment — lowest first"),"payment_asc");addSort(m,AppPreferences.tr(this,"Процентная ставка — больше сначала","Rate — highest first"),"rate_desc");addSort(m,AppPreferences.tr(this,"Процентная ставка — меньше сначала","Rate — lowest first"),"rate_asc");addSort(m,AppPreferences.tr(this,"По типу","By type"),"type");m.show();}
    private void addSort(PopupMenu m,String label,String value){String visible=value.equals(sortMode)?"✓ "+label:label;m.getMenu().add(visible).setOnMenuItemClickListener(x->{sortMode=value;render();return true;});}

    private List<ReminderScheduler.PaymentReminder> filterSort(List<ReminderScheduler.PaymentReminder> src){List<ReminderScheduler.PaymentReminder> out=new ArrayList<>();for(ReminderScheduler.PaymentReminder r:src)if("all".equals(filterType)||filterType==null||filterType.equals(ReminderScheduler.normalizeType(r.type)))out.add(r);Comparator<ReminderScheduler.PaymentReminder> c;if("created_new".equals(sortMode))c=(a,b)->Long.compare(b.createdAt,a.createdAt);else if("created_old".equals(sortMode))c=(a,b)->Long.compare(a.createdAt,b.createdAt);else if("name_asc".equals(sortMode))c=(a,b)->a.title.compareToIgnoreCase(b.title);else if("name_desc".equals(sortMode))c=(a,b)->b.title.compareToIgnoreCase(a.title);else if("debt_desc".equals(sortMode))c=(a,b)->Double.compare(ReminderScheduler.remainingDebt(b),ReminderScheduler.remainingDebt(a));else if("debt_asc".equals(sortMode))c=(a,b)->Double.compare(ReminderScheduler.remainingDebt(a),ReminderScheduler.remainingDebt(b));else if("payment_desc".equals(sortMode))c=(a,b)->Double.compare(nextAmount(b),nextAmount(a));else if("payment_asc".equals(sortMode))c=(a,b)->Double.compare(nextAmount(a),nextAmount(b));else if("rate_desc".equals(sortMode))c=(a,b)->Double.compare(b.annualRate,a.annualRate);else if("rate_asc".equals(sortMode))c=(a,b)->Double.compare(a.annualRate,b.annualRate);else if("type".equals(sortMode))c=(a,b)->{int t=Integer.compare(typeOrder(a.type),typeOrder(b.type));return t!=0?t:Long.compare(ReminderScheduler.nextPaymentMillis(a),ReminderScheduler.nextPaymentMillis(b));};else c=(a,b)->{boolean ad=ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(a.type)),bd=ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(b.type));if(ad!=bd)return ad?1:-1;return Long.compare(ReminderScheduler.nextPaymentMillis(a),ReminderScheduler.nextPaymentMillis(b));};Collections.sort(out,c);return out;}
    private double nextAmount(ReminderScheduler.PaymentReminder r){int i=ReminderScheduler.nextPaymentIndex(r);return i<0?0:ReminderScheduler.paymentAmount(r,i);}private int typeOrder(String t){String x=ReminderScheduler.normalizeType(t);if(ReminderScheduler.TYPE_CREDIT.equals(x))return 0;if(ReminderScheduler.TYPE_MORTGAGE.equals(x))return 1;if(ReminderScheduler.TYPE_AUTO.equals(x))return 2;if(ReminderScheduler.TYPE_INSTALLMENT.equals(x))return 3;return 4;}

    private View summary(List<ReminderScheduler.PaymentReminder> items){double debt=0,due=0,paidMonth=0,remainMonth=0,earlyMonth=0,totalInterest=0,paidInterest=0,remainInterest=0,overdue=0,dep=0,depIncome=0,depFinal=0;int overdueCount=0;boolean hasDebt=false,hasDeposit=false;ReminderScheduler.PaymentReminder nearest=null;int nearestIndex=-1;for(ReminderScheduler.PaymentReminder r:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type))){hasDeposit=true;dep+=r.principal;depIncome+=ReminderScheduler.depositExpectedIncome(r);depFinal+=ReminderScheduler.depositFinalAmount(r);continue;}hasDebt=true;debt+=ReminderScheduler.remainingDebt(r);due+=ReminderScheduler.dueThisMonth(r);paidMonth+=ReminderScheduler.paidThisMonth(r);remainMonth+=ReminderScheduler.remainingThisMonth(r);earlyMonth+=ReminderScheduler.earlyRepaymentThisMonth(r);totalInterest+=ReminderScheduler.totalInterest(r);paidInterest+=ReminderScheduler.paidInterest(r);remainInterest+=ReminderScheduler.remainingInterest(r);overdue+=ReminderScheduler.overdueAmount(r);overdueCount+=ReminderScheduler.overdueCount(r);int ix=ReminderScheduler.nextPaymentIndex(r);if(ix>=0&&(nearest==null||ReminderScheduler.buildDueDate(r,ix).getTimeInMillis()<ReminderScheduler.buildDueDate(nearest,nearestIndex).getTimeInMillis())){nearest=r;nearestIndex=ix;}}
        MaterialCardView card=card();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(16),dp(18),dp(18));card.addView(box);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);box.addView(head);head.addView(text(AppPreferences.tr(this,"Общая сводка","Summary"),19,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));TextView smile=text(statusFace(overdueCount,nearest,nearestIndex,hasPaidEarlySoon(items)),32,statusColor(overdueCount,nearest,nearestIndex,hasPaidEarlySoon(items)),true);smile.setGravity(Gravity.CENTER);head.addView(smile,new LinearLayout.LayoutParams(dp(46),dp(46)));
        addLabelValue(box,AppPreferences.tr(this,"Общий остаток долга","Total remaining debt"),FormatUtils.money(this,debt),25,R.color.text_main);addLabelValue(box,AppPreferences.tr(this,"К оплате в этом месяце","Due this month"),FormatUtils.money(this,remainMonth),21,remainMonth>0?R.color.primary:R.color.success);
        LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams stp=new LinearLayout.LayoutParams(-1,-2);stp.setMargins(0,dp(10),0,0);box.addView(stats,stp);stats.addView(statBox(AppPreferences.tr(this,"Оплачено по графику","Scheduled paid"),paidMonth,R.color.success),new LinearLayout.LayoutParams(0,-2,1f));stats.addView(countStatBox(AppPreferences.tr(this,"Осталось платежей в этом месяце","Payments left this month"),remainingPaymentsThisMonth(items),remainingPaymentsThisMonth(items)>0?R.color.warning:R.color.success),new LinearLayout.LayoutParams(0,-2,1f));
        if(overdueCount>0){TextView od=text(AppPreferences.tr(this,"Просрочено","Overdue")+": "+overdueCount+" · "+FormatUtils.money(this,overdue),14,R.color.danger,true);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,-2);op.setMargins(0,dp(10),0,0);box.addView(od,op);}if(nearest!=null&&nearestIndex>=0){long nearestDay=dayKey(ReminderScheduler.buildDueDate(nearest,nearestIndex).getTimeInMillis());double nextTotal=0;int nextCount=0;for(ReminderScheduler.PaymentReminder rr:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(rr.type)))continue;int ni=ReminderScheduler.nextPaymentIndex(rr);if(ni>=0&&dayKey(ReminderScheduler.buildDueDate(rr,ni).getTimeInMillis())==nearestDay){nextTotal+=ReminderScheduler.paymentAmount(rr,ni);nextCount++;}}int color=paymentUrgencyColor(nearest,nearestIndex);String nextText=AppPreferences.tr(this,"Следующий платёж","Next payment")+": "+FormatUtils.date(this,nearestDay)+" · "+nextCount+AppPreferences.tr(this,nextCount==1?" платёж · всего ":" платежа · всего ",nextCount==1?" payment · total ":" payments · total ")+FormatUtils.money(this,nextTotal);TextView next=text(nextText,15,color,true);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.setMargins(0,dp(12),0,0);box.addView(next,np);}double nextMonth=nextMonthTotal(items);int nextMonthCount=nextMonthCount(items);TextView nm=text(AppPreferences.tr(this,"В следующем месяце","Next month")+": "+nextMonthCount+AppPreferences.tr(this,nextMonthCount==1?" платёж · ":" платежа · ",nextMonthCount==1?" payment · ":" payments · ")+FormatUtils.money(this,nextMonth),14,R.color.primary,true);LinearLayout.LayoutParams nmp=new LinearLayout.LayoutParams(-1,-2);nmp.setMargins(0,dp(8),0,0);box.addView(nm,nmp);
        if(hasDebt){divider(box);box.addView(text(AppPreferences.tr(this,"Переплата по активным кредитам","Active loan interest"),17,R.color.text_main,true));summaryLine(box,AppPreferences.tr(this,"Общая переплата","Total interest"),totalInterest);summaryLine(box,AppPreferences.tr(this,"Уже выплачено процентов","Interest already paid"),paidInterest);summaryLine(box,AppPreferences.tr(this,"Осталось выплатить процентов","Interest remaining"),remainInterest);}if(hasDeposit){divider(box);box.addView(text(AppPreferences.tr(this,"Активные вклады","Active deposits"),17,R.color.text_main,true));summaryLine(box,AppPreferences.tr(this,"Во вкладах","Deposited"),dep);summaryLine(box,AppPreferences.tr(this,"Ожидаемый доход","Expected income"),depIncome);summaryLine(box,AppPreferences.tr(this,"Итого к получению","Expected total"),depFinal);}return card;}
    private boolean hasPaidEarlySoon(List<ReminderScheduler.PaymentReminder> items){long now=System.currentTimeMillis(),limit=now+3L*24L*60L*60L*1000L;for(ReminderScheduler.PaymentReminder r:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type)))continue;for(int i=0;i<r.months;i++){long due=ReminderScheduler.buildDueDate(r,i).getTimeInMillis();if(due>=now&&due<=limit&&ReminderScheduler.isPaid(r,i)&&ReminderScheduler.paidAt(r,i)>0&&ReminderScheduler.paidAt(r,i)<due)return true;}}return false;}private String statusFace(int overdue,ReminderScheduler.PaymentReminder r,int index,boolean paidEarly){if(overdue>0)return "☹";if(paidEarly)return "☺";if(r==null||index<0)return "☺";int c=paymentUrgencyColor(r,index);return c==R.color.danger?"☹":c==R.color.warning?"☻":"☺";}private int statusColor(int overdue,ReminderScheduler.PaymentReminder r,int index,boolean paidEarly){if(overdue>0)return R.color.danger;if(paidEarly)return R.color.success;if(r==null||index<0)return R.color.success;return paymentUrgencyColor(r,index);}
    private int paymentUrgencyColor(ReminderScheduler.PaymentReminder r,int i){if(ReminderScheduler.isPaid(r,i))return R.color.success;if(ReminderScheduler.isOverdue(r,i)||ReminderScheduler.isToday(r,i))return R.color.danger;long days=daysUntil(ReminderScheduler.buildDueDate(r,i).getTimeInMillis());if(days<=3)return R.color.danger;if(days<=7)return R.color.warning;return R.color.success;}
    private long daysUntil(long dueMillis){Calendar now=Calendar.getInstance();now.set(Calendar.HOUR_OF_DAY,0);now.set(Calendar.MINUTE,0);now.set(Calendar.SECOND,0);now.set(Calendar.MILLISECOND,0);Calendar due=Calendar.getInstance();due.setTimeInMillis(dueMillis);due.set(Calendar.HOUR_OF_DAY,0);due.set(Calendar.MINUTE,0);due.set(Calendar.SECOND,0);due.set(Calendar.MILLISECOND,0);return (due.getTimeInMillis()-now.getTimeInMillis())/(24L*60L*60L*1000L);}
    private long dayKey(long millis){Calendar c=Calendar.getInstance();c.setTimeInMillis(millis);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    private boolean inNextMonth(long millis){Calendar target=Calendar.getInstance();target.add(Calendar.MONTH,1);Calendar d=Calendar.getInstance();d.setTimeInMillis(millis);return d.get(Calendar.YEAR)==target.get(Calendar.YEAR)&&d.get(Calendar.MONTH)==target.get(Calendar.MONTH);}
    private int remainingPaymentsThisMonth(List<ReminderScheduler.PaymentReminder> items){int count=0;Calendar now=Calendar.getInstance();int y=now.get(Calendar.YEAR),m=now.get(Calendar.MONTH);for(ReminderScheduler.PaymentReminder r:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type)))continue;for(int i=0;i<r.months;i++){if(ReminderScheduler.isPaid(r,i))continue;Calendar d=ReminderScheduler.buildDueDate(r,i);if(d.get(Calendar.YEAR)==y&&d.get(Calendar.MONTH)==m)count++;}}return count;}
    private double nextMonthTotal(List<ReminderScheduler.PaymentReminder> items){double total=0;for(ReminderScheduler.PaymentReminder r:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type)))continue;for(int i=0;i<r.months;i++)if(!ReminderScheduler.isPaid(r,i)&&inNextMonth(ReminderScheduler.buildDueDate(r,i).getTimeInMillis()))total+=ReminderScheduler.paymentAmount(r,i);}return total;}
    private int nextMonthCount(List<ReminderScheduler.PaymentReminder> items){int count=0;for(ReminderScheduler.PaymentReminder r:items){if(ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type)))continue;for(int i=0;i<r.months;i++)if(!ReminderScheduler.isPaid(r,i)&&inNextMonth(ReminderScheduler.buildDueDate(r,i).getTimeInMillis()))count++;}return count;}

    private View countStatBox(String label,int value,int color){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.addView(text(label,12,R.color.text_secondary,false));b.addView(text(String.valueOf(value),15,color,true));return b;}
    private View statBox(String label,double value,int color){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.addView(text(label,12,R.color.text_secondary,false));b.addView(text(FormatUtils.money(this,value),15,color,true));return b;}private void addLabelValue(LinearLayout b,String l,String v,int size,int color){TextView label=text(l,13,R.color.text_secondary,false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(10),0,dp(2));b.addView(label,lp);b.addView(text(v,size,color,true));}private void divider(LinearLayout b){View v=new View(this);v.setBackgroundColor(ContextCompat.getColor(this,R.color.border));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(1));p.setMargins(0,dp(16),0,dp(14));b.addView(v,p);}private void summaryLine(LinearLayout p,String l,double v){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(9),0,0);p.addView(r,rp);r.addView(text(l,14,R.color.text_secondary,false),new LinearLayout.LayoutParams(0,-2,1f));r.addView(text(FormatUtils.money(this,v),15,R.color.text_main,true));}

    private View paymentCard(ReminderScheduler.PaymentReminder r){MaterialCardView card=card();card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->openDetails(r));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(14),dp(10),dp(16));card.addView(c);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setGravity(Gravity.CENTER_VERTICAL);c.addView(top);top.addView(text(FormatUtils.typeLabel(this,r.type),13,R.color.primary,true),new LinearLayout.LayoutParams(0,-2,1f));TextView more=text("⋮",28,R.color.text_main,true);more.setGravity(Gravity.CENTER);more.setOnClickListener(v->actions(more,r));top.addView(more,new LinearLayout.LayoutParams(dp(52),dp(46)));LinearLayout titleRow=new LinearLayout(this);titleRow.setOrientation(LinearLayout.HORIZONTAL);titleRow.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams trp=new LinearLayout.LayoutParams(-1,-2);trp.setMargins(0,dp(2),0,dp(8));c.addView(titleRow,trp);titleRow.addView(text(r.title,20,R.color.text_main,true),new LinearLayout.LayoutParams(0,-2,1f));TextView created=text(AppPreferences.tr(this,"Создано: ","Created: ")+FormatUtils.date(this,r.createdAt),11,R.color.text_secondary,false);titleRow.addView(created);
        boolean deposit=ReminderScheduler.TYPE_DEPOSIT.equals(ReminderScheduler.normalizeType(r.type));if(deposit){c.addView(text(AppPreferences.tr(this,"Сумма вклада: ","Deposit: ")+FormatUtils.money(this,r.principal),15,R.color.text_secondary,false));c.addView(text(AppPreferences.tr(this,"Ожидаемый доход: ","Expected income: ")+FormatUtils.money(this,ReminderScheduler.depositExpectedIncome(r)),16,R.color.text_main,false));}else{c.addView(text(AppPreferences.tr(this,"Исходная сумма: ","Original amount: ")+FormatUtils.money(this,r.baseAmount),14,R.color.text_secondary,false));c.addView(text(AppPreferences.tr(this,"Остаток долга: ","Remaining debt: ")+FormatUtils.money(this,ReminderScheduler.remainingDebt(r)),16,R.color.text_main,true));int ni=ReminderScheduler.nextPaymentIndex(r);if(ni>=0)c.addView(text((ReminderScheduler.PAYMENT_DIFFERENTIAL.equals(r.paymentType)?AppPreferences.tr(this,"Следующий платёж: ","Next payment: "):AppPreferences.tr(this,"Ежемесячно: ","Monthly: "))+FormatUtils.money(this,ReminderScheduler.paymentAmount(r,ni)),16,R.color.text_main,false));c.addView(text(AppPreferences.tr(this,"Переплата: ","Interest: ")+FormatUtils.money(this,ReminderScheduler.totalInterest(r)),13,R.color.text_secondary,false));}
        if(!deposit){int special=paidEarlyNearDue(r);int ix=special>=0?special:ReminderScheduler.nextPaymentIndex(r);TextView next=text("",14,R.color.text_secondary,false);if(ix>=0){if(special>=0){next.setText(AppPreferences.tr(this,"Оплачено заранее: ","Paid early: ")+FormatUtils.date(this,ReminderScheduler.buildDueDate(r,ix).getTimeInMillis()));next.setTextColor(ContextCompat.getColor(this,R.color.success));}else if(ReminderScheduler.isOverdue(r,ix)){long days=Math.max(1,(System.currentTimeMillis()-ReminderScheduler.buildDueDate(r,ix).getTimeInMillis())/(24L*60L*60L*1000L));next.setText(AppPreferences.tr(this,"Просрочен платёж: ","Overdue payment: ")+FormatUtils.money(this,ReminderScheduler.paymentAmount(r,ix))+" · "+days+AppPreferences.tr(this," дн."," d."));next.setTextColor(ContextCompat.getColor(this,R.color.danger));next.setTypeface(null,android.graphics.Typeface.BOLD);}else{next.setText(AppPreferences.tr(this,"Следующий платёж: ","Next payment: ")+FormatUtils.date(this,ReminderScheduler.buildDueDate(r,ix).getTimeInMillis()));next.setTextColor(ContextCompat.getColor(this,paymentUrgencyColor(r,ix)));next.setTypeface(null,android.graphics.Typeface.BOLD);}}else next.setText(AppPreferences.tr(this,"Срок завершён","Term completed"));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.setMargins(0,dp(8),0,0);c.addView(next,np);}if(!r.soundEnabled)c.addView(text("🔇 "+AppPreferences.tr(this,"Без звука","Muted"),12,R.color.text_secondary,false));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(12));card.setLayoutParams(cp);return card;}
    private int paidEarlyNearDue(ReminderScheduler.PaymentReminder r){long now=System.currentTimeMillis(),limit=now+3L*24L*60L*60L*1000L;for(int i=0;i<r.months;i++){long due=ReminderScheduler.buildDueDate(r,i).getTimeInMillis();if(due>=now&&due<=limit&&ReminderScheduler.isPaid(r,i)&&ReminderScheduler.paidAt(r,i)<due)return i;}return -1;}
    private void actions(View a,ReminderScheduler.PaymentReminder r){PopupMenu m=new PopupMenu(this,a);String mute=r.soundEnabled?AppPreferences.tr(this,"Без звука","Mute"):AppPreferences.tr(this,"Включить звук","Enable sound"),hist=AppPreferences.tr(this,"История изменений","Change history"),arch=AppPreferences.tr(this,"В архив","Archive"),del=AppPreferences.tr(this,"Удалить","Delete");m.getMenu().add(mute);m.getMenu().add(hist);m.getMenu().add(arch);m.getMenu().add(del);m.setOnMenuItemClickListener(x->{String s=x.getTitle().toString();if(s.equals(mute))ReminderScheduler.setMuted(this,r.id,r.soundEnabled);else if(s.equals(hist)){Intent i=new Intent(this,HistoryActivity.class);i.putExtra(HistoryActivity.EXTRA_REMINDER_ID,r.id);startActivity(i);return true;}else if(s.equals(arch))ReminderScheduler.archive(this,r.id);else ReminderScheduler.moveToTrash(this,r.id);render();return true;});m.show();}

    private void showDisclaimer(){
        if(isFinishing()||AppPreferences.isPaymentsDisclaimerAccepted(this))return;
        new AlertDialog.Builder(this)
                .setTitle(AppPreferences.tr(this,"Важно","Important"))
                .setMessage(AppPreferences.tr(this,"Расчёты в приложении носят ориентировочный информационный характер. Фактические суммы платежей, процентов, остатка долга, досрочного погашения и экономии могут отличаться от данных банка. Для точных сумм ориентируйтесь на договор и информацию вашего банка.","Calculations in the app are estimates for information only. Actual payments, interest, balance, early-repayment amounts and savings may differ from bank figures. Use your contract and bank information for exact amounts."))
                .setCancelable(false)
                .setPositiveButton(AppPreferences.tr(this,"Понятно, продолжить","I understand, continue"),(d,w)->AppPreferences.setPaymentsDisclaimerAccepted(this,true))
                .show();
    }

    private void showNavigationMenu(View anchor){if(drawer!=null)drawer.openDrawer(GravityCompat.START);}

    private TextView navigationItem(String icon,String label,boolean selected,Dialog dialog,Class<?> target,boolean calculators){
        TextView item=navigationText(icon+"   "+label,selected);item.setOnClickListener(v->{dialog.dismiss();if(target==PaymentsActivity.class)return;Intent i=new Intent(this,target);if(calculators)i.putExtra(MainActivity.EXTRA_SHOW_CALCULATORS,true);startActivity(i);});return item;
    }
    private TextView navigationText(String value,boolean selected){TextView t=new TextView(this);t.setText(value);t.setTextSize(17);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(22),0,dp(12),0);t.setTextColor(ContextCompat.getColor(this,selected?R.color.primary:R.color.text_main));if(selected){t.setTypeface(null,android.graphics.Typeface.BOLD);t.setBackgroundColor(Color.argb(24,47,111,235));}return t;}

    private void showInfo(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton(AppPreferences.tr(this,"Понятно","OK"),null).show();}
    private String infoForText(String source){
        if(source==null)return null;String s=source.toLowerCase(java.util.Locale.ROOT);
        if(s.startsWith("общая сводка")||s.startsWith("summary"))return AppPreferences.tr(this,"Сводка учитывает только активные записи. Архивные кредиты и их выгода здесь не суммируются.","The summary includes active items only. Archived loans and archived savings are excluded.");
        if(s.startsWith("общий остаток долга")||s.startsWith("total remaining debt"))return AppPreferences.tr(this,"Сумма текущего основного долга по всем активным кредитам.","Current principal balance across all active loans.");
        if(s.startsWith("к оплате в этом месяце")||s.startsWith("due this month"))return AppPreferences.tr(this,"Фактически оставшаяся сумма обычных платежей текущего месяца. После полной оплаты месяца становится 0 ₽.","Remaining scheduled installments for the current month. It becomes 0 after the month is fully paid.");
        if(s.startsWith("оплачено по графику")||s.startsWith("scheduled paid"))return AppPreferences.tr(this,"Только обычные ежемесячные платежи, отмеченные оплаченными в текущем месяце. Досрочные платежи сюда не входят.","Normal scheduled installments paid this month. Early repayments are not included.");
        if(s.startsWith("осталось платежей в этом месяце")||s.startsWith("payments left this month"))return AppPreferences.tr(this,"Количество обычных платежей текущего месяца, которые ещё не отмечены оплаченными.","Number of normal installments this month that are not yet marked paid.");
        if(s.startsWith("досрочно внесено")||s.startsWith("early repayment"))return AppPreferences.tr(this,"Досрочные погашения показываются отдельно и не смешиваются с обычными платежами.","Early repayments are shown separately from normal installments.");
        if(s.startsWith("просроч")||s.startsWith("overdue"))return AppPreferences.tr(this,"Неоплаченные платежи, дата которых уже прошла.","Unpaid installments whose due date has passed.");
        if(s.startsWith("следующий платёж")||s.startsWith("next payment"))return AppPreferences.tr(this,"Ближайшая дата неоплаченного платежа. Если в этот день несколько платежей, показывается их количество и общая сумма.","Nearest unpaid due date. If several payments fall on that day, their count and total are combined.");
        if(s.startsWith("в следующем месяце")||s.startsWith("next month"))return AppPreferences.tr(this,"Количество и общая сумма обычных платежей следующего календарного месяца.","Count and total of normal scheduled installments in the next calendar month.");
        if(s.startsWith("переплата")||s.startsWith("общая переплата")||s.startsWith("interest:" )||s.startsWith("total interest"))return AppPreferences.tr(this,"Расчётная сумма процентов по графику. Банк может округлять и начислять проценты иначе.","Estimated interest under the schedule. Bank rounding and accrual rules may differ.");
        if(s.startsWith("уже выплачено процентов")||s.startsWith("interest already paid"))return AppPreferences.tr(this,"Расчётная процентная часть платежей, уже отмеченных оплаченными.","Estimated interest portion of installments already marked paid.");
        if(s.startsWith("осталось выплатить процентов")||s.startsWith("interest remaining"))return AppPreferences.tr(this,"Ориентировочные будущие проценты по текущему активному графику.","Estimated future interest under the current active schedule.");
        if(s.startsWith("ваша выгода")||s.startsWith("your savings"))return AppPreferences.tr(this,"Расчётная экономия только по активным кредитам от применённых досрочных погашений и рефинансирований. Выгода архивных кредитов сохраняется в архиве и истории.","Estimated savings for active loans only from applied early repayments and refinancing. Archived-loan savings remain in archive/history.");
        if(s.startsWith("исходная сумма")||s.startsWith("original amount"))return AppPreferences.tr(this,"Первоначальная сумма записи до последующих платежей и изменений графика.","Original amount before later payments and schedule changes.");
        if(s.startsWith("остаток долга")||s.startsWith("remaining debt"))return AppPreferences.tr(this,"Ориентировочный текущий основной долг с учётом отмеченных оплат и применённых изменений.","Estimated current principal after marked payments and applied changes.");
        if(s.startsWith("ежемесячно")||s.startsWith("monthly:"))return AppPreferences.tr(this,"Плановый ближайший обычный платёж по текущему графику.","Planned next normal installment under the current schedule.");
        if(s.startsWith("сумма вклада")||s.startsWith("deposit:"))return AppPreferences.tr(this,"Основная сумма активного вклада.","Principal amount of the active deposit.");
        if(s.startsWith("ожидаемый доход")||s.startsWith("expected income"))return AppPreferences.tr(this,"Ориентировочный доход по введённой ставке и сроку вклада.","Estimated deposit income from the entered rate and term.");
        if(s.startsWith("активные записи")||s.startsWith("active items"))return AppPreferences.tr(this,"Количество записей, которые сейчас находятся в «Мои платежи» и не перенесены в архив или корзину.","Number of items currently active in My payments, excluding archive and trash.");
        return null;
    }

    private void openDetails(ReminderScheduler.PaymentReminder r){Intent i=new Intent(this,PaymentDetailsActivity.class);i.putExtra(PaymentDetailsActivity.EXTRA_REMINDER_ID,r.id);startActivity(i);}
    private MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(ContextCompat.getColor(this,R.color.card_background));c.setRadius(dp(18));c.setStrokeColor(ContextCompat.getColor(this,R.color.border));c.setStrokeWidth(dp(1));c.setCardElevation(dp(1));return c;}private TextView top(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setClickable(true);return t;}private TextView text(String s,int z,int color,boolean bold){TextView t=new TextView(this);String info=infoForText(s);t.setText(info==null?s:s+"  ⓘ");t.setTextSize(z);t.setTextColor(ContextCompat.getColor(this,color));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);if(info!=null){t.setClickable(true);String title=s==null?"":s.replaceAll("[·:].*$","").trim();t.setOnClickListener(v->showInfo(title,info));}return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
